begin;
select plan(1);
do $$declare org_a uuid:=gen_random_uuid();org_b uuid:=gen_random_uuid();admin_user uuid:=gen_random_uuid();viewer_user uuid:=gen_random_uuid();product uuid;route uuid;order_id uuid;first_op uuid;operation_count integer;visible_count integer;begin
  insert into organizations(id,name)values(org_a,'Execution Test A'),(org_b,'Execution Test B');
  insert into auth.users(id,email)values(admin_user,'execution-admin@example.test'),(viewer_user,'execution-viewer@example.test');
  insert into maintenance_members(user_id,organization_id,role)values(admin_user,org_a,'admin'),(viewer_user,org_b,'viewer');
  insert into operations(organization_id,code,name)values(org_a,'EXEC_PICK','Execution Pick'),(org_a,'EXEC_PRINT','Execution Print');
  insert into work_centers(organization_id,code,name)values(org_a,'EXEC_CENTER','Execution Center');
  insert into routings(organization_id,code,name,revision,status,effective_from)values(org_a,'EXEC_STANDARD','Execution Standard',1,'DRAFT',current_date)returning id into route;
  insert into routing_operations(organization_id,routing_id,sequence,operation_id,work_center_id)select org_a,route,v.seq,o.id,w.id from(values(10,'EXEC_PICK'),(20,'EXEC_PRINT'))v(seq,code)join operations o on o.organization_id=org_a and o.code=v.code cross join lateral(select id from work_centers where organization_id=org_a and code='EXEC_CENTER')w;
  update routings set status='ACTIVE'where id=route;
  insert into products(organization_id,sku,default_routing_id)values(org_a,'EXEC-SKU',route)returning id into product;
  perform set_config('request.jwt.claim.sub',admin_user::text,true);set local role authenticated;
  insert into production_orders(organization_id,order_no,source_order_no,product_id,planned_quantity,planned_date,planner_priority)values(org_a,'PO-EXEC-1','130000001',product,100,current_date,10)returning id into order_id;
  select count(*)into operation_count from production_order_operations where production_order_id=order_id;if operation_count<>2 then raise exception 'Routing operations were not snapshotted';end if;
  if(select routing_revision_snapshot from production_orders where id=order_id)<>1 then raise exception 'Routing revision was not snapshotted';end if;
  select id into first_op from production_order_operations where production_order_id=order_id order by sequence limit 1;
  update production_order_operations set status='IN_PROGRESS',actual_quantity=25 where id=first_op;
  update production_order_operations set status='COMPLETED',actual_quantity=100 where id=first_op;
  if(select last_completed_operation_code from v_production_order_execution where production_order_id=order_id)<>'EXEC_PICK'then raise exception 'Last completed operation calculation failed';end if;
  reset role;update routings set status='INACTIVE'where id=route;update operations set name='Changed Master Name'where organization_id=org_a and code='EXEC_PICK';
  if(select operation_name_snapshot from production_order_operations where id=first_op)<>'Execution Pick'then raise exception 'Historical operation snapshot changed with master';end if;
  perform set_config('request.jwt.claim.sub',viewer_user::text,true);set local role authenticated;
  select count(*)into visible_count from production_orders where organization_id=org_a;if visible_count<>0 then raise exception 'Production order organization isolation failed';end if;
  begin insert into production_orders(organization_id,order_no)values(org_b,'UNAUTHORIZED');raise exception 'Unauthorized production order write was accepted';exception when insufficient_privilege then null;when raise_exception then if sqlerrm='Unauthorized production order write was accepted'then raise;end if;end;
end$$;
select pass('Phase C execution snapshots, progress calculations and RLS behave correctly');
select * from finish();
rollback;
