import Link from"next/link";import{AppShell}from"@/components/app-shell";import{releaseQueue,type ReleaseQueueRow}from"@/lib/release-queue";
const statuses=["ALL","ELIGIBLE","NOT_APPROVED","BLOCKED","FUTURE_DUE","UNKNOWN"];
const fmt=(v:string|null)=>v?new Intl.DateTimeFormat("en-AU",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(v)):"—";
const qty=(v:number)=>new Intl.NumberFormat("en-AU").format(Number(v)||0);
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const p=await searchParams,all=await releaseQueue(),status=p.status??"ALL",q=(p.q??"").toLowerCase(),priority=p.priority??"",process=p.process??"",blocker=p.blocker??"",customer=(p.customer??"").toLowerCase(),due=p.due??"";
 const hasProcess=(r:ReleaseQueueRow,k:string)=>Number(r[`${k}_qty`as keyof ReleaseQueueRow]??0)>0;
 const rows=all.filter(r=>(status==="ALL"||r.release_status===status)&&(!q||r.order_no.toLowerCase().includes(q)||(r.customer_name??"").toLowerCase().includes(q))&&(!customer||(r.customer_name??"").toLowerCase().includes(customer))&&(!priority||String(r.source_priority??"")===priority)&&(!process||hasProcess(r,process))&&(!blocker||r.release_blockers.includes(blocker))&&(!due||r.date_due?.slice(0,10)===due)).sort((a,b)=>(a.source_priority??999)-(b.source_priority??999)||(a.date_due??"").localeCompare(b.date_due??"")||a.order_no.localeCompare(b.order_no));
 const counts=Object.fromEntries(statuses.slice(1).map(s=>[s,all.filter(r=>r.release_status===s).length]));
 return <AppShell><section className="release-queue"><header className="hero compact"><div><p className="eyebrow">ORACLE · RELEASE CONTROL</p><h2>Orders to Be Released</h2><p>Approval, route and production-process evidence from the current Oracle snapshot.</p></div><div className="hero-stat"><b>{all.length}</b><span>Operational orders</span></div></header>
 <div className="release-kpis">{statuses.slice(1,5).map(s=><Link key={s} href={`?status=${s}`} className={s.toLowerCase()}><span>{s.replace("_"," ")}</span><strong>{counts[s]}</strong><small>orders</small></Link>)}</div>
 <form className="release-filters"><input name="q" defaultValue={p.q} placeholder="Order number or customer"/><select name="status" defaultValue={status}>{statuses.map(s=><option key={s}>{s}</option>)}</select><input name="customer" defaultValue={p.customer} placeholder="Customer"/><select name="priority" defaultValue={priority}><option value="">All priorities</option>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select><input type="date" name="due" defaultValue={due}/><select name="process" defaultValue={process}><option value="">All processes</option>{["dtg","underprint","uv","hats","finished","stickers","visual","production","custom_emb","eyewear"].map(x=><option value={x} key={x}>{x.replace("_"," ").toUpperCase()}</option>)}</select><select name="blocker" defaultValue={blocker}><option value="">All blockers</option>{["ROUTE_BLOCKED","STOP_SHIP","CUSTOM_EMB"].map(x=><option key={x}>{x}</option>)}</select><button>Apply</button><Link href="/production/release-queue">Clear</Link></form>
 <p className="release-result">Showing <b>{rows.length}</b> of {all.length} operational orders. Zero-production orders remain in diagnostics only.</p>
 <div className="release-table"><table><thead><tr><th>Priority</th><th>Order #</th><th>Customer</th><th>Received</th><th>Due</th><th>Release status</th><th>Blockers</th><th>DTG</th><th>Underprint</th><th>UV</th><th>Hats</th><th>Custom Emb</th><th>Route</th><th>Stop Ship</th></tr></thead><tbody>{rows.map(r=><tr key={r.order_no}><td>{r.source_priority??"—"}</td><td><details><summary>{r.order_no}</summary><div className="release-detail"><b>Classification evidence</b><span>Cost centre: {r.cost_centre??"—"}</span><span>Route: {r.route_id??"—"}</span><span>Stop ship: {r.stop_ship_flag??"—"}</span><span>Blockers: {r.release_blockers.join(", ")||"None"}</span><span>Finished {qty(r.finished_qty)} · Stickers {qty(r.stickers_qty)} · Visual {qty(r.visual_qty)} · Production {qty(r.production_qty)} · Eyewear {qty(r.eyewear_qty)}</span></div></details></td><td>{r.customer_name??"—"}</td><td>{fmt(r.date_received)}</td><td>{fmt(r.date_due)}</td><td><b className={`release-status ${r.release_status.toLowerCase()}`}>{r.release_status.replace("_"," ")}</b></td><td>{r.release_blockers.join(", ")||"—"}</td><td>{qty(r.dtg_qty)}</td><td>{qty(r.underprint_qty)}</td><td>{qty(r.uv_qty)}</td><td>{qty(r.hats_qty)}</td><td>{qty(r.custom_emb_qty)}</td><td>{r.route_id??"—"}</td><td>{r.stop_ship_flag??"—"}</td></tr>)}</tbody></table></div></section></AppShell>}
