import { addRoutingOperation, assignProductRouting, cloneRoutingRevision, createRouting, moveRoutingOperation, removeRoutingOperation, setRoutingStatus } from "./actions";
import { routingMaster } from "@/lib/routing-master";

export const dynamic = "force-dynamic";
export default async function RoutingsPage() {
  const data = await routingMaster();
  const routings = data.routings as any[], steps = data.routingOperations as any[], operations = data.operations as any[], centers = data.centers as any[], products = data.products as any[];
  return <main className="page-shell"><section className="hero"><p className="eyebrow">PRODUCTION ENGINEERING · PHASE B</p><h1>Routing master</h1><p>Define what should happen. Source events will validate what actually happened in a later phase.</p></section>
    <section className="panel"><h2>Create routing revision</h2><form action={createRouting} className="form-grid"><input name="code" placeholder="DTG_STANDARD" required/><input name="name" placeholder="DTG Standard" required/><input name="revision" type="number" min="1" defaultValue="1" required/><select name="status" defaultValue="DRAFT"><option>DRAFT</option><option>ACTIVE</option><option>INACTIVE</option></select><input name="effective_from" type="date"/><button disabled={!data.canManage}>Create revision</button></form></section>
    <section className="panel"><h2>Routing editor</h2>{routings.map((routing)=><article key={routing.id} className="panel"><header><strong>{routing.code} · Rev {routing.revision}</strong> <span>{routing.status}</span><form action={cloneRoutingRevision}><input type="hidden" name="routing_id" value={routing.id}/><button disabled={!data.canManage}>New revision</button></form>{routing.status==="DRAFT"&&<form action={setRoutingStatus}><input type="hidden" name="routing_id" value={routing.id}/><input type="hidden" name="status" value="ACTIVE"/><button disabled={!data.canManage}>Activate</button></form>}{routing.status==="ACTIVE"&&<form action={setRoutingStatus}><input type="hidden" name="routing_id" value={routing.id}/><input type="hidden" name="status" value="INACTIVE"/><button disabled={!data.canManage}>Deactivate</button></form>}</header><table><thead><tr><th>Seq</th><th>Operation</th><th>Work center</th><th>Required</th><th>Setup</th><th>Rate</th><th>Queue</th><th></th></tr></thead><tbody>{steps.filter((step)=>step.routing_id===routing.id).map((step)=><tr key={step.id}><td>{step.sequence}</td><td>{step.operations?.code}</td><td>{step.work_centers?.code ?? "—"}</td><td>{step.required?"Yes":"Optional"}</td><td>{step.setup_minutes??"—"}</td><td>{step.run_rate??"—"}</td><td>{step.queue_minutes??"—"}</td><td>{routing.status==="DRAFT"&&<><form action={moveRoutingOperation}><input type="hidden" name="id" value={step.id}/><input type="hidden" name="routing_id" value={routing.id}/><button name="direction" value="up" disabled={!data.canManage}>↑</button><button name="direction" value="down" disabled={!data.canManage}>↓</button></form><form action={removeRoutingOperation}><input type="hidden" name="id" value={step.id}/><button disabled={!data.canManage}>Remove</button></form></>}</td></tr>)}</tbody></table>
      {routing.status==="DRAFT"&&<form action={addRoutingOperation} className="form-grid"><input type="hidden" name="routing_id" value={routing.id}/><input name="sequence" type="number" min="1" step="10" placeholder="Sequence" required/><select name="operation_id" required><option value="">Operation</option>{operations.filter((operation)=>operation.active).map((operation)=><option key={operation.id} value={operation.id}>{operation.code}</option>)}</select><select name="work_center_id"><option value="">No work center</option>{centers.map((center)=><option key={center.id} value={center.id}>{center.code}</option>)}</select><label><input name="required" type="checkbox" defaultChecked/> Required</label><input name="setup_minutes" type="number" min="0" step="0.001" placeholder="Setup min"/><input name="run_rate" type="number" min="0.001" step="0.001" placeholder="Run rate"/><input name="queue_minutes" type="number" min="0" step="0.001" placeholder="Queue min"/><input name="instructions" placeholder="Instructions"/><button disabled={!data.canManage}>Add operation</button></form>}</article>)}</section>
    <section className="panel"><h2>Product default routing</h2><form action={assignProductRouting} className="form-grid"><select name="product_id" required><option value="">Product</option>{products.map((product)=><option key={product.id} value={product.id}>{product.sku}</option>)}</select><select name="routing_id" required><option value="">Routing revision</option>{routings.map((routing)=><option key={routing.id} value={routing.id}>{routing.code} · Rev {routing.revision}</option>)}</select><button disabled={!data.canManage}>Assign routing</button></form></section>
  </main>;
}
