import {parseConnectorEnv} from "./env";import {testOracleConnection} from "./oracle";import {OracleSourceReader} from "./source-reader";import {syncOnce} from "./sync";import{agentTick,heartbeatOnce}from"./agent";import{refreshDtgDailyActuals,refreshDtgHistoricalActuals}from"./dtg-daily-actuals";import{refreshUpDailyActuals,refreshUpHistoricalActuals}from"./up-daily-actuals";
async function main(){const env=parseConnectorEnv(process.env);const command=process.argv[2];
 if(command==="oracle:test"){await testOracleConnection(env);console.info("Oracle connectivity verified.");return}
 if(command==="oracle:inspect"){const source=new OracleSourceReader(env);try{console.info(await source.inspect())}finally{await source.close()}return}
 if(command==="sync:once"){const source=new OracleSourceReader(env);try{const result=await syncOnce(env,source);console.info(`Sync batch accepted: ${result.batchId}; raw audit replication disabled`)}finally{await source.close()}return}
 if(command==="agent:heartbeat"){const identity=await heartbeatOnce(env);console.info(`HEARTBEAT_OK project=${identity.projectRef} agent=${env.AGENT_ID}`);return}
 if(command==="agent:tick"){const outcome=await agentTick(env);if(outcome.status==="EXECUTED")console.info(`SYNC_SUCCESS trigger=${outcome.triggerType} batch=${outcome.result.batchId} raw_audit=disabled`);else console.info("SYNC_IDLE");return}
 if(command==="dtg:refresh"){const from=process.argv[3],to=process.argv[4];if(!from||!to)throw new Error("Expected dtg:refresh YYYY-MM-DD YYYY-MM-DD");const source=new OracleSourceReader(env);try{const result=await refreshDtgDailyActuals(env,source,{from,to});console.info(`DTG_DAILY_REFRESH accepted=${result.accepted} from=${from} to=${to}`)}finally{await source.close()}return}
 if(command==="dtg:backfill"){const from=process.argv[3],to=process.argv[4];if(!from||!to)throw new Error("Expected dtg:backfill YYYY-MM-DD YYYY-MM-DD");const source=new OracleSourceReader(env);try{const result=await refreshDtgHistoricalActuals(env,source,from,to);console.info(`DTG_AGGREGATE_BACKFILL accepted=${result.accepted} windows=${result.windows} from=${from} to=${to}`)}finally{await source.close()}return}
 if(command==="up:refresh"){const from=process.argv[3],to=process.argv[4];if(!from||!to)throw new Error("Expected up:refresh YYYY-MM-DD YYYY-MM-DD");const source=new OracleSourceReader(env);try{const result=await refreshUpDailyActuals(env,source,{from,to});console.info(`UP_DAILY_REFRESH accepted=${result.accepted} from=${from} to=${to}`)}finally{await source.close()}return}
 if(command==="up:backfill"){const from=process.argv[3],to=process.argv[4];if(!from||!to)throw new Error("Expected up:backfill YYYY-MM-DD YYYY-MM-DD");const source=new OracleSourceReader(env);try{const result=await refreshUpHistoricalActuals(env,source,from,to);console.info(`UP_AGGREGATE_BACKFILL accepted=${result.accepted} windows=${result.windows} from=${from} to=${to}`)}finally{await source.close()}return}
 throw new Error("Expected oracle:test, sync:once, agent:heartbeat, agent:tick, dtg:refresh, dtg:backfill, up:refresh or up:backfill");
}
main().catch(error=>{console.error(error instanceof Error?error.message:"Connector failed");process.exitCode=1});
