import oracledb,{type Connection} from "oracledb";import type {SyncPayload} from "@tsd/shared";import {resolveOracleCredential} from "./credential";import {mapAudit,mapOrder,mapReleaseOrderLine,mapStock,mapWorkbank} from "./mapping";import type {SourceReader} from "./sync";import type {ConnectorEnv} from "./types";
const SQL={
 orders:`select v.ORDER_NO,v.DATE_RECD,v.DATE_DUE,v.DATE_RELEASED,v.STATUS,v.SUB_STATUS,v.CUSTOMER,v.CUST_NAME,v.SHIP_TO_NAME,v.CUSTOMER_STATE,v.CITY,v.DELIVERY_DESC1,v.CLIENT_SO_NUMBER,v.PRIORITY,oh.SITE,oh.ROUTE_ID,oh.COST_CENTRE,oh.STOP_SHIP_FLAG,oh.STATUS HEAD_STATUS,oh.TIMESTAMP from IS_ORDER_VIEW_SALE_V v join IS_ORDER_HEAD oh on oh.ORDER_NO=v.ORDER_NO and oh.DATE_COMPLETED is null`,
 releaseLines:`select ol.ORDER_NO,ol.LINE_NUMBER,ol.PRODUCT,ol.CLIENT,ol.QTY_LCD,ol.ORIG_REF3,p.GROUP_CODE,p.NAME PRODUCT_NAME,ol.TIMESTAMP SOURCE_UPDATED_AT from IS_ORDER_LINE ol join IS_ORDER_HEAD oh on oh.ORDER_NO=ol.ORDER_NO left join IS_PRODUCT p on p.CODE=ol.PRODUCT and p.CLIENT=ol.CLIENT where oh.SITE='B' and oh.ORDER_NO like '13%' and oh.STATUS=1 and oh.DATE_DUE between SYSDATE-30 and SYSDATE+30`,
 workbank:`select w.WB_ROWID,w.ID,w.ONO,w.CUSTOMER,w.CUSTOMER_NAME,w.DTM_DUE,w.FROM_LOC,w.FROM_ZONE,w.TO_LOC,w.FROM_PACK_ID,w.TO_PACK_ID,w.PRIORITY,w.PROD,w.DESCRIPTION,w.PRODUCT_GROUP,w.QTY,w.WEIGHT,w.PACKDESC,nvl(w.QUEUE,nvl(w.WK_QUEUE,'UNASSIGNED')) QUEUE,w.WK_QUEUE,w.ISIS_TASK,case when upper(w.FROM_ZONE)='DTGS' then p.PROD_X_5 else null end PROD_X_5 from IS_WORKBANK_V w join IS_ORDER_HEAD oh on oh.ORDER_NO=w.ONO and oh.DATE_COMPLETED is null left join IS_PRODUCT p on p.CLIENT=w.CLIENT and p.CODE=w.PROD where (upper(w.FROM_ZONE) in ('PG11','DTGS','PG01','PG1H','PG1A','PG1D') or (upper(w.FROM_ZONE)='PWL1' and upper(w.TO_LOC) like 'PWL1%'))`,
 stock:`select PRODUCT,PACK_ID,LOCATION,ZONE,DTIME,QTY,WEIGHT from IS_STOCK_V where upper(CLIENT)='TSD' and PRODUCT like '#%' and LOCATION not like 'CONS%' and LOCATION not like 'DROPZONE%' and (upper(LOCATION) like '%UNDERPRINT%' or upper(ZONE)='PWL1')`,
 audit:`select a.AUDIT_ID,a.ONO,a.USERNAME,a.FROM_ZONE,a.TO_ZONE,a.FROM_LOCATION,a.TO_LOCATION,a.PRODUCT,a.FROM_PACK_ID,a.TO_PACK_ID,a.QTY,a.WEIGHT,a.TIMESTAMP,a.QUEUE,a.ISIS_TASK,p.PROD_X_5 from ISIS_AUDIT a left join IS_PRODUCT p on p.CLIENT=a.CLIENT and p.CODE=a.PRODUCT where a.AUDIT_ID > :after_id and (upper(a.QUEUE)='PCOR' or upper(a.ISIS_TASK)='PCOR' or (upper(a.FROM_ZONE)='PG11' and upper(a.TO_ZONE)='DTGS') or upper(a.FROM_ZONE)='PWL1' or upper(a.TO_ZONE)='PWL1' or upper(a.FROM_LOCATION) like '%UNDERPRINT%' or upper(a.TO_LOCATION) like '%UNDERPRINT%') order by a.AUDIT_ID`,
} as const;
export class OracleSourceReader implements SourceReader{
 private connection?:Connection;constructor(private readonly env:ConnectorEnv){}
 private async get(){if(!this.connection){const c=resolveOracleCredential(this.env);this.connection=await oracledb.getConnection({connectString:this.env.ORACLE_CONNECT_STRING,user:c.username,password:c.password})}return this.connection}
 private async rows(sql:string,binds:Record<string,string>={}){const result=await (await this.get()).execute<Record<string,unknown>>(sql,binds,{outFormat:oracledb.OUT_FORMAT_OBJECT,fetchArraySize:1000});return result.rows??[]}
 async inspect(){const rows=await this.rows(`select (select count(*) from IS_ORDER_VIEW_SALE_V where ORDER_NO in (select ORDER_NO from IS_ORDER_HEAD where DATE_COMPLETED is null)) as ORDERS_COUNT,(select count(*) from IS_ORDER_HEAD oh where oh.SITE='B' and oh.ORDER_NO like '13%' and oh.STATUS=1 and oh.DATE_DUE between SYSDATE-30 and SYSDATE+30) as RELEASE_ORDERS_COUNT,(select count(*) from IS_ORDER_LINE ol join IS_ORDER_HEAD oh on oh.ORDER_NO=ol.ORDER_NO left join IS_PRODUCT p on p.CODE=ol.PRODUCT and p.CLIENT=ol.CLIENT where oh.SITE='B' and oh.ORDER_NO like '13%' and oh.STATUS=1 and oh.DATE_DUE between SYSDATE-30 and SYSDATE+30) as RELEASE_LINES_COUNT,(select count(*) from IS_WORKBANK_V w join IS_ORDER_HEAD oh on oh.ORDER_NO=w.ONO where oh.DATE_COMPLETED is null and (upper(w.FROM_ZONE) in ('PG11','DTGS','PG01','PG1H','PG1A','PG1D') or (upper(w.FROM_ZONE)='PWL1' and upper(w.TO_LOC) like 'PWL1%'))) as WORKBANK_COUNT,(select count(*) from IS_STOCK_V where upper(CLIENT)='TSD' and PRODUCT like '#%' and LOCATION not like 'CONS%' and LOCATION not like 'DROPZONE%' and (upper(LOCATION) like '%UNDERPRINT%' or upper(ZONE)='PWL1')) as STOCK_COUNT,(select max(AUDIT_ID) from ISIS_AUDIT) as MAX_AUDIT_ID from dual`);return rows[0]}
 async readAuditBetween(from:string,to:string){const rows=await this.rows(`select a.AUDIT_ID,a.ONO,a.USERNAME,a.FROM_ZONE,a.TO_ZONE,a.FROM_LOCATION,a.TO_LOCATION,a.PRODUCT,a.FROM_PACK_ID,a.TO_PACK_ID,a.QTY,a.WEIGHT,a.TIMESTAMP,a.QUEUE,a.ISIS_TASK,p.PROD_X_5 from ISIS_AUDIT a left join IS_PRODUCT p on p.CLIENT=a.CLIENT and p.CODE=a.PRODUCT where a.TIMESTAMP>=to_date(:from_date,'YYYY-MM-DD') and a.TIMESTAMP<to_date(:to_date,'YYYY-MM-DD')+1 and (upper(a.QUEUE)='PCOR' or upper(a.ISIS_TASK)='PCOR' or (upper(a.FROM_ZONE)='PG11' and upper(a.TO_ZONE)='DTGS') or upper(a.FROM_ZONE)='PWL1' or upper(a.TO_ZONE)='PWL1' or upper(a.FROM_LOCATION) like '%UNDERPRINT%' or upper(a.TO_LOCATION) like '%UNDERPRINT%') order by a.AUDIT_ID`,{from_date:from,to_date:to});return rows.map(mapAudit)}
 async read():Promise<Pick<SyncPayload,"orders"|"releaseOrderLines"|"workbank"|"stock"|"auditEvents">>{const [orders,releaseLines,workbank,stock,audit]=await Promise.all([this.rows(SQL.orders),this.rows(SQL.releaseLines),this.rows(SQL.workbank),this.rows(SQL.stock),this.rows(SQL.audit,{after_id:this.env.AUDIT_AFTER_ID})]);return {orders:orders.map(mapOrder),releaseOrderLines:releaseLines.map(mapReleaseOrderLine),workbank:workbank.map(mapWorkbank),stock:stock.map(mapStock),auditEvents:audit.map(mapAudit)}}
 async close(){if(this.connection){await this.connection.close();this.connection=undefined}}
}
