import oracledb,{type Connection} from "oracledb";import type {SyncPayload} from "@tsd/shared";import {resolveOracleCredential} from "./credential";import {mapOrder,mapReleaseOrderLine,mapStock,mapWorkbank} from "./mapping";import type {SourceReader} from "./sync";import type {ConnectorEnv} from "./types";
import {mapOracleDtgDailyActual,oracleShiftRuleCte,type DtgShiftRule} from "./dtg-daily-actuals";
const SQL={
 orders:`select v.ORDER_NO,v.DATE_RECD,v.DATE_DUE,v.DATE_RELEASED,v.STATUS,v.SUB_STATUS,v.CUSTOMER,v.CUST_NAME,v.SHIP_TO_NAME,v.CUSTOMER_STATE,v.CITY,v.DELIVERY_DESC1,v.CLIENT_SO_NUMBER,v.PRIORITY,oh.SITE,oh.ROUTE_ID,oh.COST_CENTRE,oh.STOP_SHIP_FLAG,oh.STATUS HEAD_STATUS,oh.TIMESTAMP from IS_ORDER_VIEW_SALE_V v join IS_ORDER_HEAD oh on oh.ORDER_NO=v.ORDER_NO and oh.DATE_COMPLETED is null`,
 releaseLines:`select ol.ORDER_NO,ol.LINE_NUMBER,ol.PRODUCT,ol.CLIENT,ol.QTY_LCD,ol.ORIG_REF3,ol.RELEASED,p.GROUP_CODE,p.NAME PRODUCT_NAME,ol.TIMESTAMP SOURCE_UPDATED_AT from IS_ORDER_LINE ol join IS_ORDER_HEAD oh on oh.ORDER_NO=ol.ORDER_NO left join IS_PRODUCT p on p.CODE=ol.PRODUCT and p.CLIENT=ol.CLIENT where oh.SITE='B' and oh.ORDER_NO like '13%' and oh.STATUS=1 and oh.DATE_DUE between SYSDATE-30 and SYSDATE+30`,
 workbank:`select w.WB_ROWID,w.ID,w.ONO,w.CUSTOMER,w.CUSTOMER_NAME,w.DTM_DUE,w.FROM_LOC,w.FROM_ZONE,w.TO_LOC,w.FROM_PACK_ID,w.TO_PACK_ID,w.PRIORITY,w.PROD,w.DESCRIPTION,w.PRODUCT_GROUP,w.QTY,w.WEIGHT,w.PACKDESC,nvl(w.QUEUE,nvl(w.WK_QUEUE,'UNASSIGNED')) QUEUE,w.WK_QUEUE,w.ISIS_TASK,case when upper(w.FROM_ZONE)='DTGS' then p.PROD_X_5 else null end PROD_X_5 from IS_WORKBANK_V w join IS_ORDER_HEAD oh on oh.ORDER_NO=w.ONO and oh.DATE_COMPLETED is null left join IS_PRODUCT p on p.CLIENT=w.CLIENT and p.CODE=w.PROD where (upper(w.FROM_ZONE) in ('PG11','DTGS','PG01','PG1H','PG1A','PG1D') or (upper(w.FROM_ZONE)='PWL1' and upper(w.TO_LOC) like 'PWL1%'))`,
 stock:`select PRODUCT,PACK_ID,LOCATION,ZONE,DTIME,QTY,WEIGHT from IS_STOCK_V where upper(CLIENT)='TSD' and PRODUCT like '#%' and LOCATION not like 'CONS%' and LOCATION not like 'DROPZONE%' and (upper(LOCATION) like '%UNDERPRINT%' or upper(ZONE)='PWL1')`,
} as const;
export class OracleSourceReader implements SourceReader{
 private connection?:Connection;constructor(private readonly env:ConnectorEnv){}
 private async get(){if(!this.connection){const c=resolveOracleCredential(this.env);this.connection=await oracledb.getConnection({connectString:this.env.ORACLE_CONNECT_STRING,user:c.username,password:c.password})}return this.connection}
 private async rows(sql:string,binds:Record<string,string|number|null>={}){const result=await (await this.get()).execute<Record<string,unknown>>(sql,binds,{outFormat:oracledb.OUT_FORMAT_OBJECT,fetchArraySize:1000});return result.rows??[]}
 async inspect(){const rows=await this.rows(`select (select count(*) from IS_ORDER_VIEW_SALE_V where ORDER_NO in (select ORDER_NO from IS_ORDER_HEAD where DATE_COMPLETED is null)) as ORDERS_COUNT,(select count(*) from IS_ORDER_HEAD oh where oh.SITE='B' and oh.ORDER_NO like '13%' and oh.STATUS=1 and oh.DATE_DUE between SYSDATE-30 and SYSDATE+30) as RELEASE_ORDERS_COUNT,(select count(*) from IS_ORDER_LINE ol join IS_ORDER_HEAD oh on oh.ORDER_NO=ol.ORDER_NO where oh.SITE='B' and oh.ORDER_NO like '13%' and oh.STATUS=1 and oh.DATE_DUE between SYSDATE-30 and SYSDATE+30) as RELEASE_LINES_COUNT,(select sum(case when upper(trim(ol.RELEASED))='Y' then 1 else 0 end) from IS_ORDER_LINE ol join IS_ORDER_HEAD oh on oh.ORDER_NO=ol.ORDER_NO where oh.SITE='B' and oh.ORDER_NO like '13%' and oh.STATUS=1 and oh.DATE_DUE between SYSDATE-30 and SYSDATE+30) as RELEASED_Y,(select sum(case when upper(trim(ol.RELEASED))='N' then 1 else 0 end) from IS_ORDER_LINE ol join IS_ORDER_HEAD oh on oh.ORDER_NO=ol.ORDER_NO where oh.SITE='B' and oh.ORDER_NO like '13%' and oh.STATUS=1 and oh.DATE_DUE between SYSDATE-30 and SYSDATE+30) as RELEASED_N,(select sum(case when ol.RELEASED is null then 1 else 0 end) from IS_ORDER_LINE ol join IS_ORDER_HEAD oh on oh.ORDER_NO=ol.ORDER_NO where oh.SITE='B' and oh.ORDER_NO like '13%' and oh.STATUS=1 and oh.DATE_DUE between SYSDATE-30 and SYSDATE+30) as RELEASED_NULL,(select sum(case when ol.RELEASED is not null and upper(trim(ol.RELEASED)) not in('Y','N') then 1 else 0 end) from IS_ORDER_LINE ol join IS_ORDER_HEAD oh on oh.ORDER_NO=ol.ORDER_NO where oh.SITE='B' and oh.ORDER_NO like '13%' and oh.STATUS=1 and oh.DATE_DUE between SYSDATE-30 and SYSDATE+30) as RELEASED_OTHER,(select max(data_type) from all_tab_columns where table_name='IS_ORDER_LINE' and column_name='RELEASED') as RELEASED_DATA_TYPE,(select count(*) from(select ol.ORDER_NO,ol.LINE_NUMBER from IS_ORDER_LINE ol join IS_ORDER_HEAD oh on oh.ORDER_NO=ol.ORDER_NO where oh.SITE='B' and oh.ORDER_NO like '13%' and oh.STATUS=1 and oh.DATE_DUE between SYSDATE-30 and SYSDATE+30 group by ol.ORDER_NO,ol.LINE_NUMBER having count(*)>1)) as RELEASE_DUPLICATE_KEYS,(select count(*) from IS_WORKBANK_V w join IS_ORDER_HEAD oh on oh.ORDER_NO=w.ONO where oh.DATE_COMPLETED is null and (upper(w.FROM_ZONE) in ('PG11','DTGS','PG01','PG1H','PG1A','PG1D') or (upper(w.FROM_ZONE)='PWL1' and upper(w.TO_LOC) like 'PWL1%'))) as WORKBANK_COUNT,(select count(*) from IS_STOCK_V where upper(CLIENT)='TSD' and PRODUCT like '#%' and LOCATION not like 'CONS%' and LOCATION not like 'DROPZONE%' and (upper(LOCATION) like '%UNDERPRINT%' or upper(ZONE)='PWL1')) as STOCK_COUNT,(select max(AUDIT_ID) from ISIS_AUDIT) as MAX_AUDIT_ID from dual`);return rows[0]}
 async readDtgDailyActuals(from:string,to:string,rules:DtgShiftRule[]){if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to)||from>to)throw new Error("INVALID_DTG_REFRESH_RANGE");const connection=await this.get();await connection.commit();await connection.execute("SET TRANSACTION READ ONLY");const ruleCte=oracleShiftRuleCte(rules);const rows=await this.rows(`with rules as (${ruleCte.sql}),source_rows as (select a.AUDIT_ID,a.USERNAME,a.QTY,a.TIMESTAMP event_at,p.PROD_X_5,to_number(to_char(a.TIMESTAMP,'SSSSS')) event_seconds from ISIS_AUDIT a left join IS_PRODUCT p on p.CLIENT=a.CLIENT and p.CODE=a.PRODUCT where a.TIMESTAMP>=to_date(:from_date,'YYYY-MM-DD') and a.TIMESTAMP<to_date(:to_date,'YYYY-MM-DD')+2 and upper(a.QUEUE)='PCOR' and upper(a.ISIS_TASK)='PCOR' and upper(a.FROM_ZONE)='DTGS' and upper(a.TO_ZONE)='PWL1'),classified as (select s.*,coalesce(r.shift_code,'OUT_OF_SHIFT') shift_code,case when r.shift_code is not null and r.cross_midnight=1 and s.event_seconds<r.end_seconds then trunc(s.event_at)-1 else trunc(s.event_at) end operational_date from source_rows s left join rules r on r.weekday=1+(case when r.cross_midnight=1 and s.event_seconds<r.end_seconds then trunc(s.event_at)-1 else trunc(s.event_at) end-trunc(case when r.cross_midnight=1 and s.event_seconds<r.end_seconds then trunc(s.event_at)-1 else trunc(s.event_at) end,'IW')) and r.effective_from<=case when r.cross_midnight=1 and s.event_seconds<r.end_seconds then trunc(s.event_at)-1 else trunc(s.event_at) end and (r.effective_to is null or r.effective_to>=case when r.cross_midnight=1 and s.event_seconds<r.end_seconds then trunc(s.event_at)-1 else trunc(s.event_at) end) and ((r.cross_midnight=1 and (s.event_seconds>=r.start_seconds or s.event_seconds<r.end_seconds)) or (r.cross_midnight=0 and s.event_seconds>=r.start_seconds and s.event_seconds<r.end_seconds))) select to_char(operational_date,'YYYY-MM-DD') OPERATIONAL_DATE,shift_code,coalesce(upper(trim(USERNAME)),'UNATTRIBUTED') MACHINE_CODE,count(*) GARMENTS,sum(QTY*case when trim(PROD_X_5)='1 / 2' then 2 when regexp_like(trim(PROD_X_5),'^[0-9]+([.][0-9]+)?$') then to_number(trim(PROD_X_5)) else null end) PRINTS,count(*) SOURCE_EVENT_COUNT,min(AUDIT_ID) SOURCE_MIN_AUDIT_ID,max(AUDIT_ID) SOURCE_MAX_AUDIT_ID,to_char(max(event_at),'YYYY-MM-DD"T"HH24:MI:SS') SOURCE_MAX_EVENT_AT,sum(case when trim(PROD_X_5)='1 / 2' or regexp_like(trim(PROD_X_5),'^[0-9]+([.][0-9]+)?$') then 0 else 1 end) INVALID_MULTIPLIER_COUNT from classified where operational_date between to_date(:from_date,'YYYY-MM-DD') and to_date(:to_date,'YYYY-MM-DD') group by operational_date,shift_code,coalesce(upper(trim(USERNAME)),'UNATTRIBUTED') order by OPERATIONAL_DATE,SHIFT_CODE,MACHINE_CODE`,{...ruleCte.binds,from_date:from,to_date:to});return rows.map(mapOracleDtgDailyActual)}
 async read():Promise<Pick<SyncPayload,"orders"|"releaseOrderLines"|"workbank"|"stock">>{const [orders,releaseLines,workbank,stock]=await Promise.all([this.rows(SQL.orders),this.rows(SQL.releaseLines),this.rows(SQL.workbank),this.rows(SQL.stock)]);return {orders:orders.map(mapOrder),releaseOrderLines:releaseLines.map(mapReleaseOrderLine),workbank:workbank.map(mapWorkbank),stock:stock.map(mapStock)}}
 async close(){if(this.connection){await this.connection.close();this.connection=undefined}}
}
