import * as XLSX from "xlsx";
export type DeputyRow={sourceRowKey:string;date:string|null;timesheetId:string|null;employeeId:string|null;personKey:string|null;name:string|null;rawArea:string|null;area:string|null;startAt:string|null;endAt:string|null;totalHours:number|null;breakHours:number;approval:"APPROVED"|"PROVISIONAL"|"INCOMPLETE";status:"ACCEPTED"|"QUARANTINED";reasons:string[];raw:Record<string,unknown>};
export const AREA_MAP:Record<string,string>={DTG:"DTG_OPERATOR",UNDERPRINT:"UP_OPERATOR","SCREEN PRINTING":"SCREEN_PRINT_CREW",SCREENPRINTING:"SCREEN_PRINT_CREW","DTG TUNNEL":"SHARED_DISPATCH","UP TUNNEL":"SHARED_DISPATCH",FLOATER:"SHARED_DISPATCH","SCREEN ROOM":"SCREEN_ROOM",PROJECT:"INDIRECT","P/H NOT WORKED":"NON_WORKED","PH NOT WORKED":"NON_WORKED"};
const A={date:["TIMESHEET DATE","DATE"],id:["TIMESHEET ID","ID"],employee:["EMPLOYEE ID"],name:["DISPLAY NAME","EMPLOYEE NAME","EMPLOYEE","NAME"],area:["AREA NAME","AREA"],start:["TIMESHEET START TIME","CLOCK IN","START TIME","START"],end:["TIMESHEET END TIME","CLOCK OUT","END TIME","END"],total:["TIMESHEET TOTAL TIME","TOTAL HOURS","TOTAL TIME","HOURS"],meal:["TIMESHEET MEAL BREAK (TOTAL)","MEAL BREAK","BREAK"],approved:["TIME APPROVED","APPROVAL STATUS","APPROVED"]}as const;
const norm=(v:unknown)=>String(v??"").trim().toUpperCase().replace(/\s+/g," ");const val=(r:Record<string,unknown>,f:keyof typeof A)=>{for(const alias of A[f]as readonly string[]){const k=Object.keys(r).find(x=>norm(x)===alias),v=k?r[k]:null;if(v!==null&&v!==undefined&&v!=="")return v}return null};
const hrs=(v:unknown)=>{if(v==null||v==="")return null;if(typeof v==="number")return v;const s=String(v).trim(),m=s.match(/^(\d+):(\d{2})/);if(m)return +m[1]+ +m[2]/60;const n=Number(s.replace(",","."));return Number.isFinite(n)?n:null};
const day=(v:unknown)=>{if(v instanceof Date)return v.toISOString().slice(0,10);if(typeof v==="number"){const d=XLSX.SSF.parse_date_code(v);return d?`${d.y}-${String(d.m).padStart(2,"0")}-${String(d.d).padStart(2,"0")}`:null}const s=String(v??"").trim(),m=s.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);if(m)return`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`;return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:null};
const ts=(fallbackDate:string|null,v:unknown,z:string)=>{
  if(!fallbackDate||v==null)return null;
  let date=fallbackDate,time:string;
  if(v instanceof Date){
    date=v.toISOString().slice(0,10);
    time=`${String(v.getUTCHours()).padStart(2,"0")}:${String(v.getUTCMinutes()).padStart(2,"0")}:${String(v.getUTCSeconds()).padStart(2,"0")}`;
  }else{
    const s=String(v).trim();
    const full=s.match(/^(\d{4}-\d{2}-\d{2}|\d{1,2}[/-]\d{1,2}[/-]\d{4})[ T](\d{1,2}:\d{2}(?::\d{2})?(?:\s*[AP]M)?)/i);
    if(full){date=day(full[1])??fallbackDate;time=full[2]}else time=s;
  }
  const am=time.match(/^(\d{1,2}):(\d{2})(?::(\d{2}))?\s*([AP]M)$/i);
  if(am){let h=+am[1]%12;if(am[4].toUpperCase()==="PM")h+=12;time=`${String(h).padStart(2,"0")}:${am[2]}:${am[3]??"00"}`}
  const x=new Date(`${date}T${time}${z==="UTC"?"Z":"+10:00"}`);
  return Number.isNaN(+x)?null:x.toISOString()
};export function parseDeputy(buffer:Buffer,filename:string,timezone:string):DeputyRow[]{const book=XLSX.read(buffer,{type:"buffer",cellDates:true}),sheet=book.Sheets[book.SheetNames[0]];if(!sheet)throw Error("Workbook has no worksheet");return XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:null}).map((raw,i)=>{const date=day(val(raw,"date")),timesheetId=String(val(raw,"id")??"").trim()||null,employeeId=String(val(raw,"employee")??"").trim()||null,name=String(val(raw,"name")??"").trim()||null,rawArea=String(val(raw,"area")??"").trim()||null,area=rawArea?AREA_MAP[norm(rawArea)]??null:null,startAt=ts(date,val(raw,"start"),timezone),endAt=ts(date,val(raw,"end"),timezone),totalHours=hrs(val(raw,"total")),explicitBreak=hrs(val(raw,"meal")),elapsedHours=startAt&&endAt?(+new Date(endAt)-+new Date(startAt))/36e5:null,breakHours=explicitBreak??(elapsedHours!=null&&totalHours!=null&&elapsedHours>=totalHours&&elapsedHours-totalHours<=2?elapsedHours-totalHours:0),a=norm(val(raw,"approved")),approval=!a?"PROVISIONAL":a.includes("APPROV")||a==="YES"?"APPROVED":a.includes("PENDING")||a.includes("PROVISION")?"PROVISIONAL":"INCOMPLETE",reasons:string[]=[];if(!date)reasons.push("INVALID_DATE");if(!employeeId&&!name)reasons.push("MISSING_EMPLOYEE");if(!area)reasons.push("UNKNOWN_AREA");if(!startAt||!endAt||new Date(endAt)<=new Date(startAt))reasons.push("INVALID_INTERVAL");if(totalHours==null||totalHours<0||totalHours>24)reasons.push("INVALID_TOTAL_HOURS");if(startAt&&endAt&&totalHours!=null){const elapsed=(+new Date(endAt)-+new Date(startAt))/36e5;if(elapsed>24)reasons.push("INVALID_ELAPSED");else if(breakHours>elapsed)reasons.push("BREAK_EXCEEDS_ELAPSED");else if(Math.abs(elapsed-breakHours-totalHours)>.1)reasons.push("HOURS_DO_NOT_RECONCILE")}if(approval==="INCOMPLETE")reasons.push("INCOMPLETE_APPROVAL");return{sourceRowKey:timesheetId??`${filename}:${i+2}`,date,timesheetId,employeeId,personKey:employeeId??(name?`NAME:${norm(name)}`:null),name,rawArea,area,startAt,endAt,totalHours,breakHours,approval,status:reasons.length?"QUARANTINED":"ACCEPTED",reasons:[...new Set(reasons)],raw}})}
