import"server-only";import{calculatePutwallSnapshot}from"@tsd/shared";import{capacityDb}from"@/lib/capacity";import{baseContext}from"@/lib/planning";export async function flowSnapshot(){const c=await baseContext(),d=capacityDb(),{data,error}=await d.from("v_current_workbank").select("order_no,to_location,from_pack_id,production_units").eq("organization_id",c.organizationId).eq("from_zone","PWL1").like("to_location","PWL1%").limit(10000);if(error)throw error;const rows=data??[],snapshot=calculatePutwallSnapshot(rows.map((x:any)=>({location:x.to_location,packId:x.from_pack_id,quantity:x.production_units===null?null:Number(x.production_units),timestamp:null})));return{...snapshot,activeOrders:new Set(rows.map((x:any)=>String(x.order_no))).size}}

export async function flowHistory(from:string,to:string){
  const c=await baseContext(),d=capacityDb(),rows:any[]=[],end=new Date(+new Date(`${to}T12:00:00Z`)+864e5).toISOString().slice(0,10);
  for(let start=0;;start+=1000){const result=await d.from("source_audit_events").select("order_no,from_pack_id,to_pack_id,from_zone,to_zone,source_weight,source_qty,production_units,event_at").eq("organization_id",c.organizationId).gte("event_at",`${from}T00:00:00+10:00`).lt("event_at",`${end}T00:00:00+10:00`).or("to_zone.eq.PWL1,from_zone.eq.PWL1").order("event_at").range(start,start+999);if(result.error)throw result.error;const page=result.data??[];rows.push(...page);if(page.length<1000)break}
  const days=new Map<string,{date:string;inOrders:Set<string>;outOrders:Set<string>;dispatchBoxes:Set<string>;inGarments:number;outGarments:number}>();
  for(const x of rows){const date=new Intl.DateTimeFormat("en-CA",{timeZone:"Australia/Brisbane",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(x.event_at)),r=days.get(date)??{date,inOrders:new Set<string>(),outOrders:new Set<string>(),dispatchBoxes:new Set<string>(),inGarments:0,outGarments:0},qty=Number(x.source_weight??x.source_qty??x.production_units??0),fromZone=String(x.from_zone??"").toUpperCase(),toZone=String(x.to_zone??"").toUpperCase();if(toZone==="PWL1"){r.inOrders.add(String(x.order_no));r.inGarments+=qty}if(fromZone==="PWL1"){r.outOrders.add(String(x.order_no));if(x.from_pack_id)r.dispatchBoxes.add(String(x.from_pack_id));r.outGarments+=qty}days.set(date,r)}
  const daily=[...days.values()].map(x=>({date:x.date,inOrders:x.inOrders.size,outOrders:x.outOrders.size,dispatchBoxes:x.dispatchBoxes.size,inGarments:x.inGarments,outGarments:x.outGarments})).sort((a,b)=>a.date.localeCompare(b.date));
  return{daily,inOrders:new Set(rows.filter(x=>String(x.to_zone??"").toUpperCase()==="PWL1").map(x=>String(x.order_no))).size,outOrders:new Set(rows.filter(x=>String(x.from_zone??"").toUpperCase()==="PWL1").map(x=>String(x.order_no))).size,dispatchBoxes:new Set(rows.filter(x=>String(x.from_zone??"").toUpperCase()==="PWL1").map(x=>x.from_pack_id).filter(Boolean)).size,dispatchGarments:daily.reduce((n,x)=>n+x.outGarments,0)}
}
