import"server-only";import{isAuthorizedAdminEmail}from"@/lib/auth";import{createClient}from"@supabase/supabase-js";import{redirect}from"next/navigation";import{createClient as sessionClient}from"@/lib/supabase/server";import{buildOrderItemMap}from"@/lib/item-mapping";import{parseScan,type ParsedScan}from"@/lib/scan-rules";
function admin(){const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Supabase server environment missing");return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})}
async function guard(){const client=await sessionClient(),{data}=await client.auth.getUser();if(!data.user)redirect("/login");if(!isAuthorizedAdminEmail(data.user.email))redirect("/login?error=unauthorized")}
type Row=Record<string,unknown>;
type LookupFailure={scan:ParsedScan|null;found:false;reason:string};
type LookupSuccess={scan:ParsedScan;found:true;orderNo:string;order:Row|null;workbank:Row[];stock:Row[];packRows:Row[];putwall:string[];locations:string[];itemMap:ReturnType<typeof buildOrderItemMap>};
export type OperationalLookupResult=LookupFailure|LookupSuccess;
async function findPack(scan:ParsedScan){const db=admin(),[stock,work]=await Promise.all([db.from("v_current_stock").select("product,pack_id,location,production_units,source_timestamp").eq("pack_id",scan.value),db.from("v_current_workbank").select("order_no,from_zone,from_location,to_location,from_pack_id,to_pack_id,product_code,production_units").or(`from_pack_id.eq.${scan.value},to_pack_id.eq.${scan.value}`)]);if(stock.error)throw stock.error;if(work.error)throw work.error;const workRows=work.data??[],stockRows=stock.data??[];const orderNo=String(workRows[0]?.order_no??stockRows[0]?.product??"").replace(/^#/,"");return{orderNo,packRows:[...stockRows,...workRows]as Row[]}}
async function findOrder(orderNo:string){const db=admin(),[order,work,stock]=await Promise.all([db.from("v_current_orders").select("order_no,ship_to_name,date_due,source_status,source_priority,delivery_desc").eq("order_no",orderNo).limit(1).maybeSingle(),db.from("v_current_workbank").select("order_no,from_zone,from_location,to_location,from_pack_id,to_pack_id,product_code,product_description,product_group,production_units,prints_per_garment,queue,task").eq("order_no",orderNo),db.from("v_current_stock").select("product,pack_id,location,production_units,source_timestamp").ilike("product",`%${orderNo}%`)]);for(const result of[order,work,stock])if(result.error)throw result.error;return{order:order.data as Row|null,workbank:(work.data??[])as Row[],stock:(stock.data??[])as Row[]}}
export async function operationalLookup(raw:string):Promise<OperationalLookupResult>{await guard();const scan=parseScan(raw);if(!scan)return{scan:null,found:false,reason:"Invalid code. Use letters, numbers, dash or underscore."};let orderNo=scan.kind==="PACK"?"":scan.value,packRows:Row[]=[];if(scan.kind!=="ORDER"){const pack=await findPack(scan);if(pack.orderNo){orderNo=pack.orderNo;packRows=pack.packRows}else if(scan.kind==="PACK")return{scan,found:false,reason:"Pack not found in the current snapshot."}}let context=await findOrder(orderNo);if(scan.kind==="AUTO"&&!context.order&&!context.workbank.length&&!context.stock.length){const pack=await findPack({...scan,kind:"PACK"});if(pack.orderNo){orderNo=pack.orderNo;packRows=pack.packRows;context=await findOrder(orderNo)}}const found=Boolean(context.order||context.workbank.length||context.stock.length);if(!found)return{scan,found:false,reason:"Order or pack not found in the current snapshot."};const locations=[...context.workbank.map(r=>String(r.to_location||r.from_location||"")),...context.stock.map(r=>String(r.location||""))].filter(Boolean);const putwall=[...new Set(locations.filter(x=>/PWL|PUTWALL/i.test(x)))];return{scan,found:true,orderNo,order:context.order,workbank:context.workbank,stock:context.stock,packRows,putwall,locations:[...new Set(locations)],itemMap:buildOrderItemMap(context.workbank)}}
