export const sumAvailable=(values:(number|null)[])=>values.some(x=>x!==null)?values.reduce<number>((n,x)=>n+(x??0),0):null;
export const ratio=(a:number|null,b:number|null)=>a===null||b===null||b<=0?null:a/b;
export function dateRange(from:string,to:string){const out:string[]=[];for(let d=new Date(`${from}T12:00:00Z`);d<=new Date(`${to}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+1))out.push(d.toISOString().slice(0,10));return out}
export function sourceStatus(to:string,productionDate:string|null,labourDate:string|null,oracleAt:string|null){const oracleDate=oracleAt?new Intl.DateTimeFormat("en-CA",{timeZone:"Australia/Brisbane",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(oracleAt)):null,dates=[productionDate,labourDate,oracleDate],available=dates.filter(Boolean)as string[];if(!available.length)return"STALE";if(dates.every(x=>x&&x>=to))return"CURRENT";if(available.some(x=>x>=to))return"PARTIAL";return"STALE"}
export type DayEvidence={date:string;actual:number|null;capacity:number|null;labour:number|null};
export type DayClass="COMPLETE"|"ZERO PRODUCTION"|"NON-OPERATIONAL"|"OUTPUT MISSING"|"LABOUR MISSING"|"SOURCE NOT INGESTED";
export function classifyPerformanceDay(x:DayEvidence,productionLatest:string|null):DayClass{const weekday=new Date(`${x.date}T12:00:00Z`).getUTCDay(),weekend=weekday===0||weekday===6,operational=x.capacity!==null||x.labour!==null||x.actual!==null;if(weekend&&!operational)return"NON-OPERATIONAL";if(productionLatest&&x.date>productionLatest)return operational?"OUTPUT MISSING":"SOURCE NOT INGESTED";if(x.actual===0)return"ZERO PRODUCTION";if(x.actual===null){if(operational)return"OUTPUT MISSING";return weekend?"NON-OPERATIONAL":"SOURCE NOT INGESTED"}if(x.labour===null)return"LABOUR MISSING";return"COMPLETE"}
export const freshnessLabel=(latest:string|null,to:string)=>!latest?"MISSING":latest>=to?"CURRENT":"STALE";
export type AgingInput={orderNo:string;units:number;age:number|null};
export type AgingBucket={key:"0"|"1"|"2"|"3"|"4"|"5"|"unknown";label:string;units:number;orders:number};
export function aggregateAging(rows:AgingInput[]){const definitions=[{key:"0",label:"0d"},{key:"1",label:"1d"},{key:"2",label:"2d"},{key:"3",label:"3d"},{key:"4",label:"4d"},{key:"5",label:">4d"},{key:"unknown",label:"Age unknown"}]as const,buckets:AgingBucket[]=definitions.map(x=>({...x,units:0,orders:0})),orders=new Map(buckets.map(x=>[x.key,new Set<string>()]));for(const row of rows){const key=row.age===null||!Number.isFinite(row.age)?"unknown":row.age>4?"5":String(Math.max(0,Math.floor(row.age)))as AgingBucket["key"],bucket=buckets.find(x=>x.key===key)!;bucket.units+=Number(row.units)||0;orders.get(key)!.add(row.orderNo)}for(const bucket of buckets)bucket.orders=orders.get(bucket.key)!.size;return{buckets,totalUnits:buckets.reduce((n,x)=>n+x.units,0),totalOrders:new Set(rows.map(x=>x.orderNo)).size,backlogUnits:buckets.find(x=>x.key==="5")!.units,backlogOrders:buckets.find(x=>x.key==="5")!.orders}}
export function workingDaysSince(value:string|null,now=new Date()){if(!value)return null;const key=(date:Date)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Australia/Brisbane",year:"numeric",month:"2-digit",day:"2-digit"}).format(date),start=new Date(`${key(new Date(value))}T12:00:00Z`),end=new Date(`${key(now)}T12:00:00Z`);if(!Number.isFinite(start.getTime()))return null;if(start>=end)return 0;let days=0;for(const cursor=new Date(start.getTime()+864e5);cursor<=end;cursor.setUTCDate(cursor.getUTCDate()+1)){const day=cursor.getUTCDay();if(day!==0&&day!==6)days++}return days}
