import"server-only";import{capacityDb}from"@/lib/capacity";import{baseContext}from"@/lib/planning";import{aggregateAging}from"@/lib/performance-rules";
// eslint-disable-next-line no-unused-vars
type PageQuery=(...range:[number,number])=>PromiseLike<any>;async function pages(make:PageQuery){const out:any[]=[];for(let from=0;;from+=1000){const result=await make(from,from+999);if(result.error)throw result.error;const batch=result.data??[];out.push(...batch);if(batch.length<1000)break}return out}
export async function performanceWorkload(){const context=await baseContext(),db=capacityDb(),[dtg,up,screen]=await Promise.all([pages((from,to)=>db.from("v_dtg_operational_orders").select("*").range(from,to)),pages((from,to)=>db.from("v_up_operational_orders").select("*").range(from,to)),pages((from,to)=>db.from("screen_print_jobs").select("*").eq("organization_id",context.organizationId).neq("status","completed").range(from,to))]),dtgRows=dtg.map(row=>({orderNo:String(row.order_no),client:String(row.ship_to_name??row.customer_name??"-"),age:row.age_days===null?null:Number(row.age_days),units:Number(row.total_prints??0),garments:Number(row.remaining_units??0),dueDate:row.date_due??null,priority:row.priority??null})),upRows=up.map(row=>({orderNo:String(row.order_no),client:String(row.ship_to_name??row.customer_name??"-"),age:row.age_days===null?null:Number(row.age_days),units:Number(row.remaining_units??0),garments:Number(row.remaining_units??0),dueDate:row.date_due??null,priority:row.priority??null})),screenRows=screen.map(row=>({orderNo:String(row.job_number??row.id),client:String(row.customer_name??"-"),age:null,units:Math.max(0,Number(row.planned_quantity??0)-Number(row.completed_quantity??0)),garments:Math.max(0,Number(row.planned_quantity??0)-Number(row.completed_quantity??0)),dueDate:row.due_date??null,priority:row.priority??null})),build=(code:string,label:string,unit:string,rows:typeof dtgRows)=>({...aggregateAging(rows),code,label,unit,rows:[...rows].sort((a,b)=>(b.age??-1)-(a.age??-1)||a.orderNo.localeCompare(b.orderNo,undefined,{numeric:true}))});return[build("DTG","DTG","prints",dtgRows),build("UP","Underprint","garments",upRows),build("SCREEN_PRINT","Screen Print","garments",screenRows)]}






