import Link from "next/link";
import { AppShell } from "@/components/app-shell";
import { labourBreakdown } from "@/lib/labour-dashboard";

const n=(x:number|null)=>x===null?"—":x.toLocaleString("en-AU",{maximumFractionDigits:1});
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Australia/Brisbane",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());

export default async function Page({searchParams}:{searchParams:Promise<{from?:string;to?:string}>}){
  const q=await searchParams,to=q.to??today(),from=q.from??new Date(+new Date(`${to}T12:00:00Z`)-13*864e5).toISOString().slice(0,10),detail=await labourBreakdown(from,to);
  const total=detail.length?detail.reduce((a,r)=>({paid:a.paid+r.paid,productive:a.productive+r.productive,regular:a.regular+r.regular,overtime:a.overtime+r.overtime}),{paid:0,productive:0,regular:0,overtime:0}):{paid:null,productive:null,regular:null,overtime:null};
  const areas=[...new Set(detail.map(r=>r.area))].map(area=>{const rows=detail.filter(r=>r.area===area),people=new Set(rows.flatMap(r=>Array.from({length:r.headcount},(_,i)=>`${r.shift}:${i}`))).size;return{area,people,productive:rows.reduce((a,r)=>a+r.productive,0),overtime:rows.reduce((a,r)=>a+r.overtime,0),output:rows[0]?.output??null,productivity:rows[0]?.productivity??null,provisional:rows.some(r=>r.provisional)}});
  return <AppShell><div className="erp-kpi"><header><div><p>DEPUTY LABOUR</p><h2>Labour performance</h2><span>Paid, productive, regular and overtime hours by operational area and shift.</span></div><form><input type="date" name="from" defaultValue={from}/><input type="date" name="to" defaultValue={to}/><button>Apply</button></form></header><section className="erp-cards"><article><span>Paid hours</span><strong>{n(total.paid)}</strong></article><article><span>Productive hours</span><strong>{n(total.productive)}</strong></article><article><span>Regular hours</span><strong>{n(total.regular)}</strong></article><article><span>Overtime hours</span><strong>{n(total.overtime)}</strong></article></section><section className="erp-cards six">{areas.map(a=><article key={a.area}><span>{a.area}</span><strong>{n(a.productive)} h</strong><small>{a.people} shift-presences · {n(a.overtime)} OT h<br/>{a.output===null?"Output N/A":`${n(a.output)} output · ${n(a.productivity)}/h`} · {a.provisional?"PROVISIONAL":"APPROVED"}</small><Link href={`/production/labour/detail?from=${from}&to=${to}&area=${a.area}`}>Audit details</Link></article>)}</section><section className="erp-table"><table><thead><tr><th>Area</th><th>Shift</th><th>People</th><th>Paid</th><th>Productive</th><th>Paid breaks</th><th>Regular</th><th>Overtime</th><th>Output</th><th>Productivity / h</th><th>Productive %</th><th>Quality</th></tr></thead><tbody>{detail.map(r=><tr key={`${r.area}|${r.shift}`}><th>{r.area}</th><td>{r.shift}</td><td>{r.headcount}</td><td>{n(r.paid)}</td><td>{n(r.productive)}</td><td>{n(r.breaks)}</td><td>{n(r.regular)}</td><td>{n(r.overtime)}</td><td>{n(r.output)}</td><td>{n(r.productivity)}</td><td>{r.paid?`${(r.productive/r.paid*100).toFixed(1)}%`:"—"}</td><td><b className={r.provisional?"warn":"good"}>{r.provisional?"PROVISIONAL":"APPROVED"}</b></td></tr>)}</tbody></table>{!detail.length&&<p className="empty">No accepted labour in this period.</p>}</section></div></AppShell>
}
