create table production_areas (id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),code text not null,name text not null,sequence integer not null default 0,active boolean not null default true,created_at timestamptz not null default now(),unique(organization_id,code));
create table production_stage_mappings (id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),production_area_id uuid not null references production_areas(id),source_field text not null check(source_field in ('from_zone','from_location')),match_pattern text not null,priority integer not null default 100,active boolean not null default true,created_at timestamptz not null default now(),unique(organization_id,source_field,match_pattern));
create table quantity_conversion_rules (id uuid primary key default gen_random_uuid(),organization_id uuid not null references organizations(id),product_group_pattern text not null default '%',multiplier numeric(14,6) not null default 1,priority integer not null default 100,active boolean not null default true,created_at timestamptz not null default now(),unique(organization_id,product_group_pattern));
alter table production_areas enable row level security;alter table production_stage_mappings enable row level security;alter table quantity_conversion_rules enable row level security;
revoke all on production_areas,production_stage_mappings,quantity_conversion_rules from anon,authenticated;grant select,insert,update,delete on production_areas,production_stage_mappings,quantity_conversion_rules to service_role;
insert into production_areas(organization_id,code,name,sequence) select id,x.code,x.name,x.sequence from organizations cross join (values ('UNMAPPED','Unmapped',0),('UP','UP Production',10),('DTG','DTG Production',20)) x(code,name,sequence) on conflict do nothing;
insert into production_stage_mappings(organization_id,production_area_id,source_field,match_pattern,priority) select a.organization_id,a.id,x.source_field,x.pattern,x.priority from production_areas a join (values ('UP','from_zone','%UP%',10),('UP','from_location','%UP%',20),('UP','from_zone','PWL1',5),('UP','from_location','PWL1',6),('DTG','from_zone','%DTG%',10),('DTG','from_location','%DTG%',20)) x(code,source_field,pattern,priority) on x.code=a.code on conflict do nothing;
insert into quantity_conversion_rules(organization_id,product_group_pattern,multiplier,priority) select id,'%',1,1000 from organizations on conflict do nothing;
create or replace view v_order_stage_summary with (security_invoker=true) as with classified as (select w.*,coalesce(mapped.code,'UNMAPPED') stage_code,coalesce(mapped.name,'Unmapped') stage_name,w.production_units*coalesce(rule.multiplier,1) converted_units from v_current_workbank w left join lateral (select a.code,a.name from production_stage_mappings m join production_areas a on a.id=m.production_area_id where m.organization_id=w.organization_id and m.active and a.active and case m.source_field when 'from_zone' then coalesce(w.from_zone,'') ilike m.match_pattern when 'from_location' then coalesce(w.from_location,'') ilike m.match_pattern end order by m.priority limit 1) mapped on true left join lateral (select r.multiplier from quantity_conversion_rules r where r.organization_id=w.organization_id and r.active and coalesce(w.product_group,'') ilike r.product_group_pattern order by r.priority limit 1) rule on true) select organization_id,order_no,max(customer_name) customer_name,min(source_due_at) due_at,stage_code,max(stage_name) stage_name,count(*) item_count,sum(converted_units) production_units,greatest(0,current_date-coalesce(min(source_due_at)::date,current_date)) age_days from classified group by organization_id,order_no,stage_code;
revoke all on v_order_stage_summary from anon,authenticated;grant select on v_order_stage_summary to service_role;

