alter table maintenance_work_orders
  add column if not exists downtime_started_at timestamptz;

update maintenance_work_orders w
set downtime_started_at = d.started_at
from maintenance_downtime_events d
where d.work_order_id = w.id
  and w.downtime_started_at is null
  and d.counts_as_downtime = true;

create or replace function maintenance_operator_start_request(p_organization_id uuid,p_asset_id uuid,p_request_type text,p_request_key text,p_actor_id uuid,p_actor_email text)returns uuid language plpgsql security definer set search_path=public as $$declare w uuid;n text;s text;stopped boolean;event_start timestamptz;begin if p_request_type not in('OPERATOR_FIX','CORRECTIVE_NOW','SCHEDULE_CORRECTIVE')then raise exception'Invalid request type';end if;perform pg_advisory_xact_lock(hashtext(p_asset_id::text));select id into w from maintenance_work_orders where organization_id=p_organization_id and operator_request_key=p_request_key limit 1;if w is not null then return w;end if;stopped:=p_request_type in('OPERATOR_FIX','CORRECTIVE_NOW');if stopped then select work_order_id into w from maintenance_downtime_events where organization_id=p_organization_id and asset_id=p_asset_id and ended_at is null order by started_at limit 1;if w is not null then return w;end if;end if;if not exists(select 1 from maintenance_assets where id=p_asset_id and organization_id=p_organization_id and active)then raise exception'Invalid asset';end if;s:=case p_request_type when'OPERATOR_FIX'then'OPEN_OPERATOR'when'CORRECTIVE_NOW'then'WAITING_MAINTENANCE'else'REQUESTED'end;event_start:=case when stopped then clock_timestamp() else null end;n:='WO-'||extract(year from now()at time zone'Australia/Brisbane')::int||'-'||lpad(nextval('maintenance_work_order_seq')::text,6,'0');insert into maintenance_work_orders(organization_id,work_order_number,asset_id,status,priority,title,requested_by,requested_by_email,request_type,maintenance_requested_at,counts_as_downtime,operator_request_key,downtime_started_at)values(p_organization_id,n,p_asset_id,s,case when p_request_type='CORRECTIVE_NOW'then'critical'when p_request_type='OPERATOR_FIX'then'high'else'medium'end,replace(p_request_type,'_',' '),p_actor_id,p_actor_email,p_request_type,case when p_request_type='CORRECTIVE_NOW'then event_start end,stopped,p_request_key,event_start)returning id into w;insert into maintenance_work_order_history(organization_id,work_order_id,from_status,to_status,changed_by,changed_by_email)values(p_organization_id,w,null,s,p_actor_id,p_actor_email);if stopped then insert into maintenance_downtime_events(organization_id,asset_id,host_asset_id,work_order_id,reason,started_at,started_by,maintenance_class,counts_as_failure,counts_as_downtime)values(p_organization_id,p_asset_id,p_asset_id,w,replace(p_request_type,'_',' '),event_start,p_actor_id,'CORRECTIVE',true,true);update maintenance_assets set status='down',updated_at=now()where id=p_asset_id;end if;return w;end$$;

revoke all on function maintenance_operator_start_request(uuid,uuid,text,text,uuid,text) from public,anon,authenticated;
grant execute on function maintenance_operator_start_request(uuid,uuid,text,text,uuid,text) to service_role;
