alter table source_orders add column if not exists site text;
create index if not exists source_orders_site_idx on source_orders(site);
create or replace view v_current_orders as select o.* from source_orders o join v_latest_completed_batch b on b.id=o.sync_batch_id;

create or replace function ingest_sync_batch(payload jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare batch_id uuid; audit_count integer;
begin
 insert into sync_batches(organization_id,status,connector_version) values((payload->>'organizationId')::uuid,'running',payload->>'connectorVersion') returning id into batch_id;
 begin
  insert into source_orders(organization_id,sync_batch_id,order_no,date_received,date_due,date_released,source_status,source_sub_status,customer_code,customer_name,ship_to_name,customer_state,city,delivery_desc,client_so_number,source_priority,site,source_updated_at) select (payload->>'organizationId')::uuid,batch_id,x."orderNo",x."dateReceived",x."dateDue",x."dateReleased",x."sourceStatus",x."sourceSubStatus",x."customerCode",x."customerName",x."shipToName",x."customerState",x.city,x."deliveryDesc",x."clientSoNumber",x."sourcePriority",x.site,x."sourceUpdatedAt" from jsonb_to_recordset(payload->'orders') x("orderNo" text,"dateReceived" timestamptz,"dateDue" timestamptz,"dateReleased" timestamptz,"sourceStatus" text,"sourceSubStatus" text,"customerCode" text,"customerName" text,"shipToName" text,"customerState" text,city text,"deliveryDesc" text,"clientSoNumber" text,"sourcePriority" integer,site text,"sourceUpdatedAt" timestamptz);
  insert into source_workbank_items(organization_id,sync_batch_id,source_row_id,order_no,customer_code,customer_name,source_due_at,from_location,from_zone,to_location,from_pack_id,to_pack_id,source_priority,product_code,product_description,product_group,source_qty,source_weight,production_units,prints_per_garment,queue,task) select (payload->>'organizationId')::uuid,batch_id,x.* from jsonb_to_recordset(payload->'workbank') x("sourceRowId" text,"orderNo" text,"customerCode" text,"customerName" text,"sourceDueAt" timestamptz,"fromLocation" text,"fromZone" text,"toLocation" text,"fromPackId" text,"toPackId" text,"sourcePriority" integer,"productCode" text,"productDescription" text,"productGroup" text,"sourceQty" numeric,"sourceWeight" numeric,"productionUnits" numeric,"printsPerGarment" numeric,queue text,task text);
  insert into source_stock_items(organization_id,sync_batch_id,product,pack_id,location,source_zone,source_timestamp,source_qty,source_weight,production_units) select (payload->>'organizationId')::uuid,batch_id,x.* from jsonb_to_recordset(payload->'stock') x(product text,"packId" text,location text,"sourceZone" text,"sourceTimestamp" timestamptz,"sourceQty" numeric,"sourceWeight" numeric,"productionUnits" numeric);
  insert into source_audit_events(organization_id,source_audit_id,order_no,username,from_zone,to_zone,from_location,to_location,product,from_pack_id,to_pack_id,source_qty,source_weight,production_units,event_at,raw_hash) select (payload->>'organizationId')::uuid,x.* from jsonb_to_recordset(payload->'auditEvents') x("sourceAuditId" text,"orderNo" text,username text,"fromZone" text,"toZone" text,"fromLocation" text,"toLocation" text,product text,"fromPackId" text,"toPackId" text,"sourceQty" numeric,"sourceWeight" numeric,"productionUnits" numeric,"eventAt" timestamptz,"rawHash" text) on conflict do nothing;
  get diagnostics audit_count=row_count;update sync_batches set status='completed',completed_at=now(),orders_count=jsonb_array_length(payload->'orders'),workbank_count=jsonb_array_length(payload->'workbank'),stock_count=jsonb_array_length(payload->'stock'),audit_new_count=audit_count where id=batch_id;
 exception when others then update sync_batches set status='failed',error_message=left(sqlerrm,1000) where id=batch_id;raise;end;return batch_id;
end $$;
alter function ingest_sync_batch(jsonb) set statement_timeout='120s';
revoke all on function ingest_sync_batch(jsonb) from public,anon,authenticated;
grant execute on function ingest_sync_batch(jsonb) to service_role;
