CREATE OR REPLACE FUNCTION public.backfill_active_wip_manufacturing_orders(p_organization_id uuid, p_source_system text DEFAULT 'ORACLE_WMS'::text)
 RETURNS TABLE(run_id uuid, staged_lines integer, created_mos integer, evidence_added integer, exceptions_added integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$declare rid uuid;staged integer:=0;mos integer:=0;ev integer:=0;ex integer:=0;cov integer:=0;r record;begin
insert into active_wip_backfill_runs(organization_id,source_system)values(p_organization_id,p_source_system)returning id into rid;
insert into production_demand_lines(organization_id,source_system,source_order_no,source_order_line_id,product_id,routing_id,routing_revision_id,source_product_code,source_description,quantity,due_date,source_priority,status,resolution_status)
select w.organization_id,p_source_system,w.order_no,'WORKBANK:'||w.source_row_id,p.id,p.default_routing_id,p.default_routing_id,w.product_code,w.product_description,w.production_units,w.source_due_at,w.source_priority,case when p.id is not null and rt.id is not null then'READY'else'EXCEPTION'end,case when p.id is null then'PRODUCT_UNMAPPED'when rt.id is null then'ROUTING_UNMAPPED'else'RESOLVED'end from v_current_workbank w left join product_source_mappings pm on pm.organization_id=w.organization_id and pm.source_system=p_source_system and pm.source_product_code=w.product_code and pm.active left join products p on p.id=pm.product_id and p.organization_id=w.organization_id and p.active left join routings rt on rt.id=p.default_routing_id and rt.organization_id=w.organization_id and rt.status='ACTIVE'and rt.active and(rt.effective_from is null or rt.effective_from<=current_date)and(rt.effective_to is null or rt.effective_to>=current_date)where w.organization_id=p_organization_id and nullif(w.source_row_id,'')is not null and w.production_units>0 and w.product_code!~'^#?[0-9]+$'and(upper(trim(coalesce(w.queue,'')))in('SP11','PCOR')or upper(trim(coalesce(w.from_location,'')))like'%UP')
on conflict(organization_id,source_system,source_order_no,source_order_line_id)do update set product_id=excluded.product_id,routing_id=excluded.routing_id,routing_revision_id=excluded.routing_revision_id,source_product_code=excluded.source_product_code,source_description=excluded.source_description,quantity=excluded.quantity,due_date=excluded.due_date,source_priority=excluded.source_priority,status=case when production_demand_lines.status='GROUPED'then'GROUPED'else excluded.status end,resolution_status=case when production_demand_lines.status='GROUPED'then production_demand_lines.resolution_status else excluded.resolution_status end,updated_at=now();get diagnostics staged=row_count;
insert into production_demand_exceptions(organization_id,production_demand_line_id,exception_type,description)select d.organization_id,d.id,d.resolution_status,'Active WIP line requires governed Product and Routing setup before MO creation.'from production_demand_lines d where d.organization_id=p_organization_id and d.source_system=p_source_system and d.status='EXCEPTION'on conflict do nothing;get diagnostics ex=row_count;
select count(*)into mos from create_manufacturing_orders(p_organization_id,p_source_system);select*into r from resolve_production_order_actual_state(p_organization_id,null);ev:=coalesce(r.evidence_added,0);ex:=ex+coalesce(r.exceptions_added,0);
insert into active_wip_coverage_exceptions(organization_id,source_system,source_order_no,stage_code,units,primary_cause,blocking_cause,explanation,status)select c.organization_id,p_source_system,c.source_order_no,c.stage_code,c.units,'PRE_EXISTING_WIP',case when not c.line_source_available then'SOURCE_LINE_MISSING'when exists(select 1 from production_demand_lines d where d.organization_id=c.organization_id and d.source_order_no=c.source_order_no and d.resolution_status='PRODUCT_UNMAPPED')then'PRODUCT_UNMAPPED'when exists(select 1 from production_demand_lines d where d.organization_id=c.organization_id and d.source_order_no=c.source_order_no and d.resolution_status in('ROUTING_UNMAPPED','ROUTING_INACTIVE'))then'ROUTING_UNMAPPED'else'MO_GENERATION_BUG'end,'Order was active before canonical MO coverage. No MO is fabricated from header-only or unmapped evidence.','ACCEPTED'from v_active_wip_mo_coverage c where c.organization_id=p_organization_id and c.canonical_mos=0 on conflict(organization_id,source_system,source_order_no,stage_code)do update set units=excluded.units,primary_cause=excluded.primary_cause,blocking_cause=excluded.blocking_cause,explanation=excluded.explanation,status='ACCEPTED',last_detected_at=now(),resolved_at=null;get diagnostics cov=row_count;ex:=ex+cov;
update active_wip_coverage_exceptions e set status='RESOLVED',resolved_at=now(),last_detected_at=now()where e.organization_id=p_organization_id and e.source_system=p_source_system and e.status<>'RESOLVED'and not exists(select 1 from v_active_wip_mo_coverage c where c.organization_id=e.organization_id and c.source_order_no=e.source_order_no and c.stage_code=e.stage_code and c.canonical_mos=0);
update active_wip_backfill_runs set completed_at=now(),staged_lines=staged,created_mos=mos,evidence_added=ev,exceptions_added=ex,status='COMPLETED'where id=rid;return query select rid,staged,mos,ev,ex;exception when others then update active_wip_backfill_runs set completed_at=now(),status='FAILED'where id=rid;raise;end$function$
;

