CREATE OR REPLACE FUNCTION public.resolve_production_order_actual_state(p_organization_id uuid, p_production_order_id uuid DEFAULT NULL::uuid)
 RETURNS TABLE(orders_resolved integer, evidence_added integer, exceptions_added integer)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$declare poid uuid;r record;o integer:=0;e integer:=0;x integer:=0;begin
with ambiguous as(select ev.source_dataset,ev.source_record_key,ev.operation_id from v_source_operation_evidence ev join production_orders po on po.organization_id=ev.organization_id and coalesce(po.source_order_no,po.order_no)=ev.order_no join production_order_operations op on op.production_order_id=po.id and op.source_operation_id=ev.operation_id where ev.organization_id=p_organization_id and(p_production_order_id is null or po.id=p_production_order_id)group by ev.source_dataset,ev.source_record_key,ev.operation_id having count(distinct po.id)>1),ins as(insert into production_routing_exceptions(organization_id,production_order_id,production_order_operation_id,exception_type,description,source_dataset,source_record_key)select distinct po.organization_id,po.id,op.id,'AMBIGUOUS_SOURCE_EVIDENCE','Evidence matches multiple MOs in the same SO; execution was not changed.',ev.source_dataset,ev.source_record_key from ambiguous a join v_source_operation_evidence ev using(source_dataset,source_record_key,operation_id)join production_orders po on po.organization_id=ev.organization_id and coalesce(po.source_order_no,po.order_no)=ev.order_no join production_order_operations op on op.production_order_id=po.id and op.source_operation_id=ev.operation_id where not exists(select 1 from production_routing_exceptions z where z.production_order_id=po.id and z.production_order_operation_id=op.id and z.exception_type='AMBIGUOUS_SOURCE_EVIDENCE'and z.source_dataset=ev.source_dataset and z.source_record_key=ev.source_record_key)returning 1)select count(*)into x from ins;
for poid in select po.id from production_orders po where po.organization_id=p_organization_id and(p_production_order_id is null or po.id=p_production_order_id)and not exists(select 1 from v_source_operation_evidence ev join production_order_operations op on op.production_order_id=po.id and op.source_operation_id=ev.operation_id where ev.organization_id=po.organization_id and ev.order_no=coalesce(po.source_order_no,po.order_no)and exists(select 1 from production_orders other join production_order_operations oop on oop.production_order_id=other.id and oop.source_operation_id=ev.operation_id where other.organization_id=po.organization_id and other.id<>po.id and coalesce(other.source_order_no,other.order_no)=ev.order_no))loop select * into r from resolve_production_order_actual_state_unambiguous(p_organization_id,poid);o:=o+coalesce(r.orders_resolved,0);e:=e+coalesce(r.evidence_added,0);x:=x+coalesce(r.exceptions_added,0);end loop;return query select o,e,x;end$function$
;

