export type KpiEvent={eventId:string;timestamp:string;operationalDate:string;shift:string;metric:string;quantity:number;quality:string};
export type KpiLabour={personKey:string;area:string;operationalDate:string;shift:string;hour:number;paidHours:number;regularHours:number;overtimeHours:number;paidBreakHours:number;productiveHours:number;approval:string};
export type KpiGrain="HOUR"|"SHIFT"|"DAY"|"WEEK"|"MONTH";
export type KpiRow={key:string;dtgActual:number|null;dtgCapacityHours:number|null;dtgTarget:number|null;dtgAchievement:number|null;putwallIn:number|null;putwallOut:number|null;accumulation:number|null;clearance:number|null;upIn:number|null;upActual:number|null;upCapacityHours:number|null;upTarget:number|null;upAchievement:number|null;screenActual:number|null;screenMachineHours:number|null;screenTarget:number|null;screenAchievement:number|null;dtgProductiveHours:number|null;upProductiveHours:number|null;screenProductiveHours:number|null;dtgOvertimeHours:number|null;upOvertimeHours:number|null;screenOvertimeHours:number|null;dispatchProductiveHours:number|null;paidHours:number|null;productiveHours:number|null;regularHours:number|null;overtimeHours:number|null;quality:string};
export type KpiEngineConfig={rates?:Partial<Record<"DTG"|"UP"|"SCREEN_PRINT",number>>;resourceCaps?:Record<string,number>};
const DEFAULT_RATE={DTG:140,UP:75,SCREEN_PRINT:350},DEFAULT_CAPS:Record<string,number>={DTG_OPERATOR:2,UP_OPERATOR:4,"UP_OPERATOR|SHIFT_1":3};
const week=(d:string)=>{const x=new Date(`${d}T12:00:00Z`),n=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()-n+1);return x.toISOString().slice(0,10)};
const keyFor=(date:string,shift:string,hour:number,grain:KpiGrain)=>grain==="HOUR"?`${date} ${String(hour).padStart(2,"0")}:00`:grain==="SHIFT"?`${date} · ${shift.replace("SHIFT_","Shift ")}`:grain==="DAY"?date:grain==="WEEK"?`Week ${week(date)}`:date.slice(0,7);
const sum=(a:number|null,b:number)=>a===null?b:a+b;
const shiftHours=(date:string,shift:string):[number,number][]=>{const friday=new Date(`${date}T12:00:00Z`).getUTCDay()===5;if(shift==="SHIFT_1")return friday?[[6,1],[7,1],[8,1],[9,1],[10,1],[11,1]]:[[6,1],[7,1],[8,1],[9,1],[10,1],[11,1],[12,1],[13,1],[14,.5]];if(shift==="SHIFT_2")return friday?[[12,1],[13,1],[14,1],[15,1],[16,1],[17,1]]:[[14,.5],[15,1],[16,1],[17,1],[18,1],[19,1],[20,1],[21,1],[22,1]];if(shift==="SHIFT_3")return friday?[[18,1],[19,1],[20,1],[21,1],[22,1]]:[[23,1],[0,1],[1,1],[2,1],[3,1],[4,1],[5,1]];return[]};
export function calculateKpis(events:KpiEvent[],labour:KpiLabour[],grain:KpiGrain,config:KpiEngineConfig={}):KpiRow[]{const RATE={...DEFAULT_RATE,...config.rates},caps={...DEFAULT_CAPS,...config.resourceCaps},rows=new Map<string,KpiRow>(),base=(key:string):KpiRow=>({key,dtgActual:null,dtgCapacityHours:null,dtgTarget:null,dtgAchievement:null,putwallIn:null,putwallOut:null,accumulation:null,clearance:null,upIn:null,upActual:null,upCapacityHours:null,upTarget:null,upAchievement:null,screenActual:null,screenMachineHours:null,screenTarget:null,screenAchievement:null,dtgProductiveHours:null,upProductiveHours:null,screenProductiveHours:null,dtgOvertimeHours:null,upOvertimeHours:null,screenOvertimeHours:null,dispatchProductiveHours:null,paidHours:null,productiveHours:null,regularHours:null,overtimeHours:null,quality:"COMPLETE"}),get=(k:string)=>{const x=rows.get(k)??base(k);rows.set(k,x);return x};
for(const e of events){if(e.quantity<=0||e.quality==="REJECTED")continue;const h=Number(new Intl.DateTimeFormat("en-AU",{timeZone:"Australia/Brisbane",hour:"2-digit",hourCycle:"h23"}).format(new Date(e.timestamp))),r=get(keyFor(e.operationalDate,e.shift,h,grain));if(e.metric==="DTG_PRINT")r.dtgActual=sum(r.dtgActual,e.quantity);if(e.metric==="DTG_PUTWALL_IN")r.putwallIn=sum(r.putwallIn,e.quantity);if(e.metric==="DTG_PUTWALL_OUT")r.putwallOut=sum(r.putwallOut,e.quantity);if(e.metric==="UP_IN")r.upIn=sum(r.upIn,e.quantity);if(e.metric==="UP_OUT")r.upActual=sum(r.upActual,e.quantity);if(e.metric==="SCREEN_PRINT")r.screenActual=sum(r.screenActual,e.quantity);if(e.metric==="SCREEN_MACHINE_HOURS")r.screenMachineHours=sum(r.screenMachineHours,e.quantity);if(e.quality!=="COMPLETE")r.quality=e.quality}
const accepted=labour.filter(x=>x.approval!=="INCOMPLETE"),cohorts=new Map<string,Set<string>>();for(const l of accepted){const c=`${l.operationalDate}|${l.shift}|${l.area}`,people=cohorts.get(c)??new Set<string>();people.add(l.personKey);cohorts.set(c,people);const r=get(keyFor(l.operationalDate,l.shift,l.hour,grain));r.paidHours=sum(r.paidHours,l.paidHours);r.productiveHours=sum(r.productiveHours,l.productiveHours);r.regularHours=sum(r.regularHours,l.regularHours);r.overtimeHours=sum(r.overtimeHours,l.overtimeHours);if(l.area==="DTG_OPERATOR"){r.dtgProductiveHours=sum(r.dtgProductiveHours,l.productiveHours);r.dtgOvertimeHours=sum(r.dtgOvertimeHours,l.overtimeHours)}if(l.area==="UP_OPERATOR"){r.upProductiveHours=sum(r.upProductiveHours,l.productiveHours);r.upOvertimeHours=sum(r.upOvertimeHours,l.overtimeHours)}if(l.area==="SCREEN_PRINT_CREW"){r.screenProductiveHours=sum(r.screenProductiveHours,l.productiveHours);r.screenOvertimeHours=sum(r.screenOvertimeHours,l.overtimeHours)}if(l.area==="SHARED_DISPATCH")r.dispatchProductiveHours=sum(r.dispatchProductiveHours,l.productiveHours);if(l.approval==="PROVISIONAL")r.quality="PROVISIONAL"}
for(const[c,people]of cohorts){const[date,shift,area]=c.split("|"),configured=caps[`${area}|${shift}`]??caps[area as keyof typeof caps]??0,headcount=Math.min(people.size,configured);if(!headcount)continue;for(const[hour,duration]of shiftHours(date,shift)){const r=get(keyFor(date,shift,hour,grain)),capacity=headcount*duration;if(area==="DTG_OPERATOR")r.dtgCapacityHours=sum(r.dtgCapacityHours,capacity);if(area==="UP_OPERATOR")r.upCapacityHours=sum(r.upCapacityHours,capacity)}}
for(const r of rows.values()){r.dtgTarget=r.dtgCapacityHours===null?null:r.dtgCapacityHours*RATE.DTG;r.upTarget=r.upCapacityHours===null?null:r.upCapacityHours*RATE.UP;r.screenTarget=r.screenMachineHours===null?null:r.screenMachineHours*RATE.SCREEN_PRINT;r.dtgAchievement=r.dtgTarget?r.dtgActual===null?null:r.dtgActual/r.dtgTarget:null;r.upAchievement=r.upTarget?r.upActual===null?null:r.upActual/r.upTarget:null;r.screenAchievement=r.screenTarget?r.screenActual===null?null:r.screenActual/r.screenTarget:null;r.accumulation=r.putwallIn===null&&r.putwallOut===null?null:(r.putwallIn??0)-(r.putwallOut??0);r.clearance=r.accumulation===null?null:-r.accumulation;if((r.dtgActual!==null&&r.dtgTarget===null)||(r.upActual!==null&&r.upTarget===null))r.quality="NO_TARGET_HOURS"}return[...rows.values()].sort((a,b)=>a.key.localeCompare(b.key))}
