import Link from "next/link";import {Activity,BarChart3,Boxes,CalendarDays,CalendarRange,ChartNoAxesCombined,CirclePause,Factory,Gauge,LayoutDashboard,PackageCheck,QrCode,ScanLine,Shirt,Users,Wrench} from "lucide-react";
const groups=[
  ["CONTROL",[["Control tower","/",LayoutDashboard],["Machine load","/production/machine-load",BarChart3],["ERP performance","/production/performance",ChartNoAxesCombined],["Production flow","/production/flow",Activity],["KPI dashboard","/kpis",Gauge]]],
  ["EXECUTION",[["Operational scan","/scan",QrCode],["UP workbank","/production/up",Shirt],["DTG workbank","/production/dtg",Factory],["Hold orders","/production/hold-orders",CirclePause],["Ready to lift","/production/ready-to-lift",PackageCheck],["Close order","/production/close-order",ScanLine],["Screen events","/production/screen-events",Factory]]],
  ["PLANNING",[["Planning","/production/planning",CalendarRange],["Daily plans","/production/plans",CalendarDays],["Capacity","/production/capacity",Gauge],["Labour dashboard","/production/labour",Users],["Deputy imports","/production/deputy",Users]]],
  ["MAINTENANCE",[["Maintenance control","/maintenance",Wrench],["Operator terminal","/maintenance/operator",QrCode],["Assets","/maintenance/assets",Factory],["Work orders","/maintenance/work-orders",CirclePause],["Preventive","/maintenance/preventive",CalendarDays],["Parts & inventory","/maintenance/inventory",Boxes],["Reports","/maintenance/reports",BarChart3]]],
  ["GOVERNANCE",[["Production stages","/production/stages",ChartNoAxesCombined],["Source data","/admin/source-data?view=orders",Boxes],["Reconciliation","/admin/reconciliation",ChartNoAxesCombined],["Sync status","/admin/sync-status",Activity]]]
] as const;
export function AppShell({children}:{children:React.ReactNode}){return <div className="frame"><aside><div className="shell-brand"><p className="brand">Tank Stream Design</p><h1>Production<br/>Control</h1><span>OPERATIONS OS</span></div><nav className="grouped-nav">{groups.map(([group,items])=><section key={group}><b>{group}</b>{items.map(([n,h,I])=><Link href={h} key={n}><I size={17}/><span>{n}</span></Link>)}</section>)}</nav><small><i className="source-pulse"/> Oracle live source<br/><b>READ ONLY</b></small></aside><main>{children}</main></div>}
