import Link from "next/link";import {Activity,BarChart3,Boxes,CalendarDays,CalendarRange,ChartNoAxesCombined,CirclePause,Factory,Gauge,LayoutDashboard,PackageCheck,QrCode,Shirt,Users,Wrench} from "lucide-react";import{DataFreshnessStatus}from"./data-freshness-status";
const groups=[
  ["CONTROL",[["Control Tower","/",LayoutDashboard],["Machine Load","/production/machine-load",BarChart3],["Performance","/production/performance",ChartNoAxesCombined]]],
  ["EXECUTION",[["DTG","/production/dtg",Factory],["Underprint","/production/up",Shirt],["Dispatch","/production/ready-to-lift",PackageCheck],["Hold","/production/hold-orders",CirclePause],["Scan","/scan",QrCode]]],
  ["PLANNING",[["Order Planning","/production/planning",CalendarRange],["Shift Plans","/production/plans",CalendarDays],["Capacity","/production/capacity",Gauge],["Labour","/production/labour",Users]]],
  ["MAINTENANCE",[["Overview","/maintenance",Wrench],["Operator","/maintenance/operator",QrCode],["Work Orders","/maintenance/work-orders",CirclePause],["Assets","/maintenance/assets",Factory],["Preventive","/maintenance/preventive",CalendarDays],["Inventory","/maintenance/inventory",Boxes]]],
  ["ADMIN / DATA",[["Imports","/production/deputy",Users],["Source Health","/admin/sync-status",Activity],["Reconciliation","/admin/reconciliation",ChartNoAxesCombined]]]
] as const;
export function AppShell({children}:{children:React.ReactNode}){return <div className="frame"><aside><div className="shell-brand"><p className="brand">Tank Stream Design</p><h1>Production<br/>Control</h1><span>OPERATIONS OS</span></div><nav className="grouped-nav">{groups.map(([group,items])=><section key={group}><b>{group}</b>{items.map(([n,h,I])=><Link href={h} key={n}><I size={17}/><span>{n}</span></Link>)}</section>)}</nav><small><i className="source-pulse"/> Oracle live source<br/><b>READ ONLY</b></small></aside><main><DataFreshnessStatus/>{children}</main></div>}
