$ErrorActionPreference='Stop'
$repo='C:\Projects\tsd-canonical-v2'; Set-Location $repo
$v2='saecycamkyvzzppxudzq';$dev='tlflipdeahgwsueerkex';$prod='gdajktoqmajipivpdude';$org='f39ce894-e039-4329-aeca-85e46e193aef'
if((git branch --show-current).Trim() -ne 'canonical-v2'){throw 'Wrong branch'}
if((Get-Content -LiteralPath 'supabase\.temp\project-ref' -Raw).Trim() -ne $v2){throw 'Wrong Supabase target'}
Add-Type @"
using System;using System.Runtime.InteropServices;public class C51Cred{[StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]public struct R{public uint a,b;public string c,d;public System.Runtime.InteropServices.ComTypes.FILETIME e;public uint f;public IntPtr g;public uint h,i;public IntPtr j;public string k,l;}[DllImport("advapi32.dll",EntryPoint="CredReadW",CharSet=CharSet.Unicode)]public static extern bool X(string t,uint y,uint z,out IntPtr p);[DllImport("advapi32.dll")]public static extern void CredFree(IntPtr p);}
"@
$p=[IntPtr]::Zero;if(-not [C51Cred]::X('Supabase CLI:supabase',1,0,[ref]$p)){throw 'credential unavailable'}
try{$c=[Runtime.InteropServices.Marshal]::PtrToStructure($p,[type][C51Cred+R]);$b=New-Object byte[] $c.f;[Runtime.InteropServices.Marshal]::Copy($c.g,$b,0,$b.Length);$t=[Text.Encoding]::UTF8.GetString($b)}finally{[C51Cred]::CredFree($p)}
$h=@{Authorization="Bearer $t";'Content-Type'='application/json'};$base='https://api.supabase.com/v1/projects'
$vp=Invoke-RestMethod -Uri "$base/$v2" -Headers $h;$dp=Invoke-RestMethod -Uri "$base/$dev" -Headers $h;$pp=Invoke-RestMethod -Uri "$base/$prod" -Headers $h
if($vp.status-ne'ACTIVE_HEALTHY'-or$dp.status-ne'INACTIVE'-or$pp.status-ne'ACTIVE_HEALTHY'){throw "Unsafe project state V2=$($vp.status) DEV=$($dp.status) PROD=$($pp.status)"}
function Q([string]$sql){$body=@{query=$sql}|ConvertTo-Json -Compress;Invoke-RestMethod -Method Post -Uri "$base/$v2/database/query" -Headers $h -Body $body}
function WriteData([string]$name,$data){$path=Join-Path $out "$name.json";ConvertTo-Json -InputObject @($data) -Depth 12|Set-Content -LiteralPath $path -Encoding utf8NoBOM;return @{dataset=$name;path="$name.json";export_count=@($data).Count;checksum_sha256=(Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant()}}
$out=Join-Path $repo 'canonical-data\product-routing';New-Item -ItemType Directory -Force -Path $out|Out-Null
$sourceRaw=Q @"
select a.source_product_code sku,max(coalesce(a.source_description,s.product_name,a.source_product_code)) description,
 case when upper(trim(s.group_code)) in('DTG_1','DTG_2') then 'DTG'
      when upper(trim(s.group_code))='UNDERPRINT' then 'UNDERPRINT'
      when upper(trim(s.group_code))='UV PRINT' then 'UV'
      when upper(trim(s.group_code))='HATS' then 'HATS'
      when upper(trim(s.group_code))='FINISHED' then 'FINISHED_GOODS'
      when upper(trim(s.group_code))='STICKERS' then 'STICKERS'
      when upper(trim(s.group_code))='VISUAL' then 'VM'
      when upper(trim(s.group_code))='EYEWEAR' then 'EYEWEAR'
      when upper(trim(s.group_code))='CUSTOM EMB' then 'CUSTOM_EMB'
      when upper(trim(s.group_code))='PROD' then 'PRODUCTION'
 end process_code,count(*) released_lines,coalesce(sum(a.production_units),0) released_units
from source_order_release_lines a join source_release_order_lines s on s.organization_id=a.organization_id and s.order_no=a.source_order_no and s.line_number=a.source_line_id
where a.released is true and nullif(trim(a.source_product_code),'') is not null
group by a.source_product_code,3 order by a.source_product_code;
"@
$source=@();foreach($item in $sourceRaw){if(($item -is [System.Collections.IEnumerable])-and($item-isnot[string])-and($item.PSObject.Properties.Name-notcontains'sku')){foreach($inner in $item){$source+=$inner}}else{$source+=$item}}
$released=(Q "select count(*) total,count(*)filter(where nullif(trim(source_product_code),'')is null)null_sku from source_order_release_lines where released is true;")[0]
$conflicts=(Q "select count(*) conflicts from(select a.source_product_code from source_order_release_lines a join source_release_order_lines s on s.organization_id=a.organization_id and s.order_no=a.source_order_no and s.line_number=a.source_line_id where a.released is true group by a.source_product_code having count(distinct upper(trim(s.group_code)))>1)q;")[0]
if([int]$released.null_sku-ne 0-or[int]$conflicts.conflicts-ne 0){throw "Dry run conflict: null SKU=$($released.null_sku), process conflicts=$($conflicts.conflicts)"}
$families=@(@{code='ADULT_TSHIRTS';name='Adult T-Shirts'},@{code='KIDS_TSHIRTS';name='Kids T-Shirts'},@{code='HOODIES_SWEATSHIRTS';name='Hoodies / Sweatshirts'},@{code='TOTES';name='Totes'},@{code='OTHER';name='Other'},@{code='UNMAPPED';name='Unmapped'})
$types=@(@{code='GARMENT';name='Garment'},@{code='ACCESSORY';name='Accessory'},@{code='UNMAPPED';name='Unmapped'})
$processes=@(@{code='UV';name='UV';sequence=40},@{code='HATS';name='Hats';sequence=50},@{code='FINISHED_GOODS';name='Finished Goods';sequence=60},@{code='STICKERS';name='Stickers';sequence=70},@{code='VM';name='VM';sequence=80},@{code='EYEWEAR';name='Eyewear';sequence=90})
$operations=@(@{code='PICKING';name='Picking'},@{code='DTG_PRINT';name='DTG Print'},@{code='PUTWALL';name='Putwall'},@{code='UNDERPRINT';name='Underprint'},@{code='SCREEN_PRINT';name='Screen Print'},@{code='DISPATCH';name='Dispatch'})
$routings=@(@{code='DTG_STANDARD';name='DTG Standard';revision=1;process_code='DTG'},@{code='UNDERPRINT_STANDARD';name='Underprint Standard';revision=1;process_code='UNDERPRINT'},@{code='SCREEN_PRINT_STANDARD';name='Screen Print Standard';revision=1;process_code='SCREEN_PRINT'})
$steps=@(@{routing_code='DTG_STANDARD';sequence=10;operation_code='PICKING'},@{routing_code='DTG_STANDARD';sequence=20;operation_code='DTG_PRINT'},@{routing_code='DTG_STANDARD';sequence=30;operation_code='PUTWALL'},@{routing_code='DTG_STANDARD';sequence=40;operation_code='DISPATCH'},@{routing_code='UNDERPRINT_STANDARD';sequence=10;operation_code='PICKING'},@{routing_code='UNDERPRINT_STANDARD';sequence=20;operation_code='UNDERPRINT'},@{routing_code='UNDERPRINT_STANDARD';sequence=30;operation_code='DISPATCH'},@{routing_code='SCREEN_PRINT_STANDARD';sequence=10;operation_code='PICKING'},@{routing_code='SCREEN_PRINT_STANDARD';sequence=20;operation_code='SCREEN_PRINT'},@{routing_code='SCREEN_PRINT_STANDARD';sequence=30;operation_code='DISPATCH'})
$opmap=@(
 @{source_field='queue';code='PAK1';process='UNDERPRINT';stage='PICKING';scope='CURRENT_SUPPORTED_PROCESS'},@{source_field='queue';code='PAK2';process='UV';stage='PICKING';scope='PROCESS_NOT_YET_SUPPORTED'},@{source_field='queue';code='PAK3';process='HATS';stage='PICKING';scope='PROCESS_NOT_YET_SUPPORTED'},@{source_field='queue';code='PAK4';process='FINISHED_GOODS';stage='PICKING';scope='NO_MO_REQUIRED'},@{source_field='queue';code='PAK5';process='STICKERS';stage='PRINTING';scope='PROCESS_NOT_YET_SUPPORTED'},@{source_field='queue';code='PAK6';process='VM';stage='PICKING';scope='PROCESS_NOT_YET_SUPPORTED'},@{source_field='queue';code='PAK7';process='SCREEN_PRINT';stage='PICKING';scope='CURRENT_SUPPORTED_PROCESS'},@{source_field='queue';code='PAK9';process='EYEWEAR';stage='PICKING';scope='PROCESS_NOT_YET_SUPPORTED'},@{source_field='queue';code='SP11';process='DTG';stage='PICKING';scope='CURRENT_SUPPORTED_PROCESS'},
 @{source_field='to_location';code='DTGMOVE';process=$null;stage='DESPATCH_CONSOLIDATION';scope='NOT_APPLICABLE'},@{source_field='to_location';code='CONSBELT';process=$null;stage='DESPATCH_CONSOLIDATION';scope='NOT_APPLICABLE'},@{source_field='to_location';code='CONSHOLD';process=$null;stage='DESPATCH_CONSOLIDATION_HOLD';scope='NOT_APPLICABLE'},@{source_field='queue';code='UNRELEASED';process=$null;stage=$null;release_status='UNRELEASED';scope='NOT_APPLICABLE'},@{source_field='queue';code='HOLD';process=$null;stage='HOLD';blocker='WAITING_REPLEN_OR_STOCKCHECK';scope='NOT_APPLICABLE'},@{source_field='queue';code='NOT APPROVED';process=$null;stage=$null;release_status='NOT_APPROVED';blocker='NOT_APPROVED';scope='NOT_APPLICABLE'})
$products=@($source|Group-Object sku|ForEach-Object{[pscustomobject]@{sku=$_.Name;description=($_.Group|Select-Object -First 1).description;family_code='UNMAPPED';type_code='UNMAPPED';source_system='ORACLE_WMS'}})
$mappings=@($products|ForEach-Object{[pscustomobject]@{source_system='ORACLE_WMS';source_product_code=$_.sku;sku=$_.sku;mapping_method='SOURCE_CONFIRMED';confidence='SOURCE_CONFIRMED'}})
$assignments=@($source|Where-Object {$_.process_code-in@('DTG','UNDERPRINT','SCREEN_PRINT')}|ForEach-Object{[pscustomobject]@{sku=$_.sku;process_code=$_.process_code;routing_code=if($_.process_code-eq'DTG'){'DTG_STANDARD'}elseif($_.process_code-eq'UNDERPRINT'){'UNDERPRINT_STANDARD'}else{'SCREEN_PRINT_STANDARD'};assignment_source='DETERMINISTIC_SOURCE';approved=$true}})
$entries=@();$entries+=WriteData 'product_families' $families;$entries+=WriteData 'product_types' $types;$entries+=WriteData 'production_processes' $processes;$entries+=WriteData 'operations' $operations;$entries+=WriteData 'routings' $routings;$entries+=WriteData 'routing_operations' $steps;$entries+=WriteData 'source_operational_code_mappings' $opmap;$entries+=WriteData 'products' $products;$entries+=WriteData 'product_source_mappings' $mappings;$entries+=WriteData 'product_routing_assignments' $assignments
$meta=@{
 product_families=@{source='VALIDATED_E5_CONFIG';dest='public.product_families';key='organization_id,code';rule='Approved family vocabulary; products remain UNMAPPED until reviewed'};product_types=@{source='VALIDATED_E5_CONFIG';dest='public.product_types';key='organization_id,code';rule='Approved type vocabulary; products remain UNMAPPED until reviewed'};production_processes=@{source='VALIDATED_E63_CONFIG';dest='public.production_processes';key='organization_id,code';rule='Approved unsupported-process vocabulary'};operations=@{source='VALIDATED_E5_CONFIG';dest='public.operations';key='organization_id,code';rule='Approved canonical operations'};routings=@{source='VALIDATED_E5_CONFIG';dest='public.routings';key='organization_id,code,revision';rule='Approved active standard routings'};routing_operations=@{source='VALIDATED_E5_CONFIG';dest='public.routing_operations';key='routing_id,sequence';rule='Approved routing sequence'};source_operational_code_mappings=@{source='VALIDATED_E63_CONFIG';dest='public.source_operational_code_mappings';key='organization_id,source_system,source_dataset,source_field,source_operational_code';rule='Validated exact operational-code map; PAK7 is Screen Print'};products=@{source='V2_ORACLE_DERIVED';dest='public.products';key='organization_id,sku';rule='Exact released Oracle SKU identity; no fuzzy matching; family/type UNMAPPED'};product_source_mappings=@{source='V2_ORACLE_DERIVED';dest='public.product_source_mappings';key='organization_id,source_system,source_product_code';rule='Exact Oracle SKU to same canonical SKU'};product_routing_assignments=@{source='CANONICAL_MERGE';dest='public.product_routing_assignments';key='organization_id,product_id,process_code';rule='Exact GROUP_CODE process plus approved standard routing; unsupported processes remain unresolved'}
}
$manifest=@{generated_at=(Get-Date).ToUniversalTime().ToString('o');target_project=$v2;source_release_lines=[int]$released.total;source_environment='V2 Oracle-derived snapshot + validated E5/E6 code config';datasets=@($entries|ForEach-Object{$m=$meta[$_.dataset];@{dataset=$_.dataset;file=$_.path;source_environment=$m.source;source_object=if($m.source-eq'V2_ORACLE_DERIVED'){'source_order_release_lines + source_release_order_lines'}else{'validated E5/E6 migration contract'};source_row_count=$_.export_count;destination=$m.dest;export_count=$_.export_count;natural_key=$m.key;checksum_sha256=$_.checksum_sha256;transformation_rule=$m.rule}})}
ConvertTo-Json $manifest -Depth 12|Set-Content -LiteralPath (Join-Path $out 'PRODUCT_ROUTING_REFERENCE_MANIFEST.json') -Encoding utf8NoBOM
function Json([string]$name){Get-Content -LiteralPath (Join-Path $out "$name.json") -Raw}
function Import-Package{
 $jFamilies=Json 'product_families';$jTypes=Json 'product_types';$jProc=Json 'production_processes';$jOps=Json 'operations';$jRoutes=Json 'routings';$jSteps=Json 'routing_operations';$jCodes=Json 'source_operational_code_mappings';$jProducts=Json 'products';$jMaps=Json 'product_source_mappings';$jAssign=Json 'product_routing_assignments'
 Q @"
begin;
delete from product_source_mappings where organization_id='$org'and source_product_code='';
delete from products where organization_id='$org'and sku=''and not exists(select 1 from production_demand_lines d where d.product_id=products.id);
insert into product_families(organization_id,code,name)select '$org',x.code,x.name from jsonb_to_recordset(`$j`$$jFamilies`$j`$::jsonb)x(code text,name text)on conflict(organization_id,code)do nothing;
insert into product_types(organization_id,code,name)select '$org',x.code,x.name from jsonb_to_recordset(`$j`$$jTypes`$j`$::jsonb)x(code text,name text)on conflict(organization_id,code)do nothing;
insert into production_processes(organization_id,code,name,sequence)select '$org',x.code,x.name,x.sequence from jsonb_to_recordset(`$j`$$jProc`$j`$::jsonb)x(code text,name text,sequence int)on conflict(organization_id,code)do nothing;
insert into operations(organization_id,code,name)select '$org',x.code,x.name from jsonb_to_recordset(`$j`$$jOps`$j`$::jsonb)x(code text,name text)on conflict(organization_id,code)do nothing;
insert into routings(organization_id,code,name,revision,status,active,effective_from)select '$org',x.code,x.name,x.revision,'DRAFT',true,current_date from jsonb_to_recordset(`$j`$$jRoutes`$j`$::jsonb)x(code text,name text,revision int,process_code text)on conflict(organization_id,code,revision)do nothing;
insert into routing_operations(organization_id,routing_id,sequence,operation_id)select '$org',r.id,x.sequence,o.id from jsonb_to_recordset(`$j`$$jSteps`$j`$::jsonb)x(routing_code text,sequence int,operation_code text)join routings r on r.organization_id='$org'and r.code=x.routing_code and r.revision=1 join operations o on o.organization_id='$org'and o.code=x.operation_code where not exists(select 1 from routing_operations ro where ro.routing_id=r.id and ro.sequence=x.sequence)on conflict(routing_id,sequence)do nothing;
update routings set status='ACTIVE',active=true where organization_id='$org'and code in('DTG_STANDARD','UNDERPRINT_STANDARD','SCREEN_PRINT_STANDARD')and revision=1 and status='DRAFT';
insert into source_operational_code_mappings(organization_id,source_system,source_dataset,source_field,source_operational_code,manufacturing_process,operational_stage,release_status,blocker_reason,mo_scope,confidence)select '$org','ORACLE_WMS','WORKBANK',x.source_field,x.code,x.process,x.stage,x.release_status,x.blocker,x.scope,'SOURCE_CONFIRMED'from jsonb_to_recordset(`$j`$$jCodes`$j`$::jsonb)x(source_field text,code text,process text,stage text,release_status text,blocker text,scope text)on conflict(organization_id,source_system,source_dataset,source_field,source_operational_code)do nothing;
insert into products(organization_id,sku,description,product_family_id,product_type_id,source_system,source_product_code)select '$org',x.sku,x.description,pf.id,pt.id,x.source_system,x.sku from jsonb_to_recordset(`$j`$$jProducts`$j`$::jsonb)x(sku text,description text,family_code text,type_code text,source_system text)join product_families pf on pf.organization_id='$org'and pf.code=x.family_code join product_types pt on pt.organization_id='$org'and pt.code=x.type_code on conflict(organization_id,sku)do nothing;
insert into product_source_mappings(organization_id,source_system,source_product_code,product_id,mapping_method,confidence,confirmed_at,notes)select '$org',x.source_system,x.source_product_code,p.id,x.mapping_method,x.confidence,now(),'Exact authoritative Oracle SKU identity; no fuzzy matching.'from jsonb_to_recordset(`$j`$$jMaps`$j`$::jsonb)x(source_system text,source_product_code text,sku text,mapping_method text,confidence text)join products p on p.organization_id='$org'and p.sku=x.sku on conflict(organization_id,source_system,source_product_code)do nothing;
insert into product_routing_assignments(organization_id,product_id,process_code,routing_id,assignment_source,approved,approved_at)select '$org',p.id,x.process_code,r.id,x.assignment_source,x.approved,now()from jsonb_to_recordset(`$j`$$jAssign`$j`$::jsonb)x(sku text,process_code text,routing_code text,assignment_source text,approved boolean)join products p on p.organization_id='$org'and p.sku=x.sku join routings r on r.organization_id='$org'and r.code=x.routing_code and r.status='ACTIVE'and r.active on conflict(organization_id,product_id,process_code)do nothing;
update products p set default_routing_id=x.routing_id,updated_at=now()from(select product_id,min(routing_id::text)::uuid routing_id from product_routing_assignments where organization_id='$org'and approved group by product_id having count(distinct routing_id)=1)x where p.id=x.product_id and p.organization_id='$org'and p.default_routing_id is null;
commit;
"@|Out-Null
}
function Counts{(Q "select (select count(*) from products)products,(select count(*) from product_source_mappings)product_maps,(select count(*) from operations)operations,(select count(*) from routings)routings,(select count(*) from routing_operations)routing_steps,(select count(*) from product_routing_assignments)assignments,(select count(*) from source_operational_code_mappings)operational_maps,(select count(*) from production_demand_lines)demands,(select count(*) from production_orders)mos,(select count(*) from manufacturing_order_lines)mo_lines;")[0]}
$before=Counts;Import-Package;$after1=Counts;Import-Package;$after2=Counts
$coverage=(Q @"
with x as(select a.*,case when upper(trim(s.group_code))in('DTG_1','DTG_2')then'DTG'when upper(trim(s.group_code))='UNDERPRINT'then'UNDERPRINT'else null end process_code from source_order_release_lines a join source_release_order_lines s on s.organization_id=a.organization_id and s.order_no=a.source_order_no and s.line_number=a.source_line_id where a.released is true),r as(select x.*,pm.product_id,pra.routing_id from x left join product_source_mappings pm on pm.organization_id=x.organization_id and pm.source_system='ORACLE_WMS'and pm.source_product_code=x.source_product_code and pm.active left join product_routing_assignments pra on pra.organization_id=x.organization_id and pra.product_id=pm.product_id and pra.process_code=x.process_code and pra.approved)
select count(*) released_lines,count(*)filter(where product_id is not null)product_mapped,count(*)filter(where product_id is null)product_unresolved,0 product_ambiguous,count(*)filter(where routing_id is not null)routing_resolved,count(*)filter(where routing_id is null)routing_unresolved,0 routing_ambiguous from r;
"@)[0]
[pscustomobject]@{datasets=$entries.Count;reference_rows=($entries|Measure-Object export_count -Sum).Sum;before=$before;after_first=$after1;after_second=$after2;second_import_product_delta=([int]$after2.products-[int]$after1.products);second_import_assignment_delta=([int]$after2.assignments-[int]$after1.assignments);coverage=$coverage;dev=$dp.status;prod=$pp.status;v2=$vp.status}|ConvertTo-Json -Depth 8
