begin;
create table public.up_daily_actuals(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id),operational_date date not null,garments numeric not null check(garments>=0),jobs bigint not null check(jobs>=0),source_event_count bigint not null check(source_event_count>=0),last_source_timestamp timestamptz,synced_at timestamptz not null default now(),status text not null default 'CURRENT' check(status in('CURRENT','STALE','MISSING')),source_system text not null default 'ORACLE_ISIS_AUDIT',calculation_version text not null default 'UP_UNDERPRINT_EXIT_DAILY_V1',unique(organization_id,operational_date));
create index up_daily_actuals_period_idx on public.up_daily_actuals(organization_id,operational_date);
alter table public.up_daily_actuals enable row level security;
create policy up_daily_actuals_read on public.up_daily_actuals for select to authenticated using(public.has_org_role(organization_id,array['viewer','operator','supervisor','maintenance','manager','admin']));
revoke all on public.up_daily_actuals from public,anon,authenticated;grant select on public.up_daily_actuals to authenticated;grant all on public.up_daily_actuals to service_role;
create function public.replace_up_daily_actuals(p_organization_id uuid,p_from date,p_to date,p_rows jsonb)returns bigint language plpgsql security definer set search_path=public as $$declare v_count bigint;begin if p_from is null or p_to is null or p_from>p_to or jsonb_typeof(p_rows)<>'array' or jsonb_array_length(p_rows)>1000 then raise exception 'INVALID_UP_DAILY_PAYLOAD';end if;if exists(select 1 from jsonb_array_elements(p_rows)r where(r->>'operationalDate')::date not between p_from and p_to or coalesce((r->>'garments')::numeric,-1)<0 or coalesce((r->>'jobs')::bigint,-1)<0 or coalesce((r->>'sourceEventCount')::bigint,-1)<0)then raise exception 'INVALID_UP_DAILY_ROW';end if;if exists(select 1 from jsonb_array_elements(p_rows)r group by r->>'operationalDate' having count(*)>1)then raise exception 'DUPLICATE_UP_DAILY_GRAIN';end if;delete from public.up_daily_actuals where organization_id=p_organization_id and operational_date between p_from and p_to;insert into public.up_daily_actuals(organization_id,operational_date,garments,jobs,source_event_count,last_source_timestamp,synced_at,status,source_system,calculation_version)select p_organization_id,(r->>'operationalDate')::date,(r->>'garments')::numeric,(r->>'jobs')::bigint,(r->>'sourceEventCount')::bigint,nullif(r->>'sourceMaxEventAt','')::timestamptz,now(),'CURRENT','ORACLE_ISIS_AUDIT',coalesce(nullif(r->>'calculationVersion',''),'UP_UNDERPRINT_EXIT_DAILY_V1')from jsonb_array_elements(p_rows)r;get diagnostics v_count=row_count;return v_count;end$$;
revoke all on function public.replace_up_daily_actuals(uuid,date,date,jsonb) from public,anon,authenticated;grant execute on function public.replace_up_daily_actuals(uuid,date,date,jsonb) to service_role;
commit;
