alter table production_demand_lines add constraint production_demand_lines_routing_identity_check check(resolution_status<>'RESOLVED' or(routing_id is not null and routing_id=routing_revision_id));
create or replace function recalculate_manufacturing_order_actual()returns trigger language plpgsql set search_path=public as $$begin update production_orders set actual_quantity=(select coalesce(sum(actual_quantity),0)from manufacturing_order_lines where manufacturing_order_id=new.manufacturing_order_id),updated_at=now()where id=new.manufacturing_order_id;return new;end$$;
create trigger recalculate_manufacturing_order_actual_change after update of actual_quantity on manufacturing_order_lines for each row execute function recalculate_manufacturing_order_actual();
create or replace function stage_workbank_demand_lines(p_organization_id uuid)returns table(staged integer,exceptions integer)language plpgsql security definer set search_path=public as $$declare s integer:=0;x integer:=0;begin
insert into production_demand_lines(organization_id,source_system,source_order_no,source_order_line_id,product_id,routing_id,routing_revision_id,source_product_code,source_description,quantity,due_date,source_priority,status,resolution_status)
select w.organization_id,'ORACLE_WMS',w.order_no,'WORKBANK:'||w.source_row_id,p.id,p.default_routing_id,p.default_routing_id,w.product_code,w.product_description,w.production_units,w.source_due_at,w.source_priority,case when p.id is not null and r.id is not null then'READY'else'EXCEPTION'end,case when p.id is null then'PRODUCT_UNMAPPED'when r.id is null then'ROUTING_UNMAPPED'else'RESOLVED'end
from v_current_workbank w left join product_source_mappings m on m.organization_id=w.organization_id and m.source_system='ORACLE_WMS'and m.source_product_code=w.product_code and m.active left join products p on p.id=m.product_id and p.organization_id=w.organization_id and p.active left join routings r on r.id=p.default_routing_id and r.organization_id=w.organization_id and r.status='ACTIVE'and r.active
where w.organization_id=p_organization_id and nullif(w.source_row_id,'')is not null and w.production_units>0
on conflict(organization_id,source_system,source_order_no,source_order_line_id)do update set source_product_code=excluded.source_product_code,source_description=excluded.source_description,due_date=excluded.due_date,source_priority=excluded.source_priority,updated_at=now()where production_demand_lines.status in('READY','EXCEPTION');get diagnostics s=row_count;
insert into production_demand_exceptions(organization_id,production_demand_line_id,exception_type,description)select d.organization_id,d.id,d.resolution_status,'Workbank line requires Product and Routing setup before MO creation.'from production_demand_lines d where d.organization_id=p_organization_id and d.status='EXCEPTION'on conflict do nothing;get diagnostics x=row_count;return query select s,x;end$$;
revoke all on function stage_workbank_demand_lines(uuid)from public,anon,authenticated;grant execute on function stage_workbank_demand_lines(uuid)to service_role;
alter table production_routing_exceptions drop constraint production_routing_exceptions_exception_type_check;
alter table production_routing_exceptions add constraint production_routing_exceptions_exception_type_check check(exception_type in('SKIPPED_OPERATION','OUT_OF_SEQUENCE','UNKNOWN_SOURCE_STAGE','UNEXPECTED_OPERATION','ROUTING_MISMATCH','SOURCE_QUANTITY_CHANGE','SOURCE_ORDER_CANCELLED','AMBIGUOUS_SOURCE_EVIDENCE'));
alter function resolve_production_order_actual_state(uuid,uuid)rename to resolve_production_order_actual_state_unambiguous;
create function resolve_production_order_actual_state(p_organization_id uuid,p_production_order_id uuid default null)returns table(orders_resolved integer,evidence_added integer,exceptions_added integer)language plpgsql security definer set search_path=public as $$declare poid uuid;r record;o integer:=0;e integer:=0;x integer:=0;begin
with ambiguous as(select ev.source_dataset,ev.source_record_key,ev.operation_id from v_source_operation_evidence ev join production_orders po on po.organization_id=ev.organization_id and coalesce(po.source_order_no,po.order_no)=ev.order_no join production_order_operations op on op.production_order_id=po.id and op.source_operation_id=ev.operation_id where ev.organization_id=p_organization_id and(p_production_order_id is null or po.id=p_production_order_id)group by ev.source_dataset,ev.source_record_key,ev.operation_id having count(distinct po.id)>1),ins as(insert into production_routing_exceptions(organization_id,production_order_id,production_order_operation_id,exception_type,description,source_dataset,source_record_key)select distinct po.organization_id,po.id,op.id,'AMBIGUOUS_SOURCE_EVIDENCE','Evidence matches multiple MOs in the same SO; execution was not changed.',ev.source_dataset,ev.source_record_key from ambiguous a join v_source_operation_evidence ev using(source_dataset,source_record_key,operation_id)join production_orders po on po.organization_id=ev.organization_id and coalesce(po.source_order_no,po.order_no)=ev.order_no join production_order_operations op on op.production_order_id=po.id and op.source_operation_id=ev.operation_id where not exists(select 1 from production_routing_exceptions z where z.production_order_id=po.id and z.production_order_operation_id=op.id and z.exception_type='AMBIGUOUS_SOURCE_EVIDENCE'and z.source_dataset=ev.source_dataset and z.source_record_key=ev.source_record_key)returning 1)select count(*)into x from ins;
for poid in select po.id from production_orders po where po.organization_id=p_organization_id and(p_production_order_id is null or po.id=p_production_order_id)and not exists(select 1 from v_source_operation_evidence ev join production_order_operations op on op.production_order_id=po.id and op.source_operation_id=ev.operation_id where ev.organization_id=po.organization_id and ev.order_no=coalesce(po.source_order_no,po.order_no)and exists(select 1 from production_orders other join production_order_operations oop on oop.production_order_id=other.id and oop.source_operation_id=ev.operation_id where other.organization_id=po.organization_id and other.id<>po.id and coalesce(other.source_order_no,other.order_no)=ev.order_no))loop select * into r from resolve_production_order_actual_state_unambiguous(p_organization_id,poid);o:=o+coalesce(r.orders_resolved,0);e:=e+coalesce(r.evidence_added,0);x:=x+coalesce(r.exceptions_added,0);end loop;return query select o,e,x;end$$;
revoke all on function resolve_production_order_actual_state(uuid,uuid),resolve_production_order_actual_state_unambiguous(uuid,uuid)from public,anon,authenticated;grant execute on function resolve_production_order_actual_state(uuid,uuid)to service_role;
create or replace view v_production_planning with(security_invoker=true)as with queues as(select organization_id,order_no,'UP'::text line,customer_name,screen,status source_status,priority source_priority,age_days,remaining_units,total_prints from v_up_operational_orders union all select organization_id,order_no,'DTG',customer_name,screen,status,priority,age_days,remaining_units,total_prints from v_dtg_operational_orders)select q.*,p.id production_order_id,p.planner_priority,coalesce(p.planner_priority,q.source_priority)effective_priority,p.planned_date,p.planned_shift_id,s.name planned_shift,p.planning_status,p.special_instruction,p.planner_note,p.blocked_reason,p.updated_at from queues q left join production_orders p on p.organization_id=q.organization_id and p.order_no=q.order_no and p.source_routing_id is null left join shift_templates s on s.id=p.planned_shift_id;grant select on v_production_planning to service_role;
