alter table source_audit_events add column if not exists queue text;alter table source_audit_events add column if not exists task text;
create or replace function rebuild_production_events(p_organization_id uuid) returns integer language plpgsql security definer set search_path=public as $$declare affected integer;begin
insert into production_events(organization_id,event_id,event_ts_utc,event_ts_local,calendar_date,operational_date,hour_bucket,shift_code,area,metric,quantity,unit,source,source_mode,source_record_key,quality_status,calculation_version)
select a.organization_id,coalesce(a.source_audit_id,a.raw_hash)||':'||m.metric,a.event_at,a.event_at at time zone'Australia/Brisbane',(a.event_at at time zone'Australia/Brisbane')::date,case when r.cross_midnight and(a.event_at at time zone'Australia/Brisbane')::time<r.end_time then(a.event_at at time zone'Australia/Brisbane')::date-1 else(a.event_at at time zone'Australia/Brisbane')::date end,extract(hour from a.event_at at time zone'Australia/Brisbane')::smallint,coalesce(r.shift_code,'OUT_OF_SHIFT'),m.area,m.metric,a.production_units,m.unit,'ORACLE_AUDIT','SQL',coalesce(a.source_audit_id,a.raw_hash),case when r.shift_code is null then'OUT_OF_SHIFT'else'COMPLETE'end,'ERP_KPI_V1'
from source_audit_events a cross join lateral(select*from(values('DTG'::text,'DTG_PRINT'::text,'prints'::text,upper(coalesce(a.queue,''))='PCOR'or upper(coalesce(a.task,''))='PCOR'),('DTG','DTG_PUTWALL_IN','garments',upper(coalesce(a.to_zone,''))='PWL1'),('DTG','DTG_PUTWALL_OUT','garments',upper(coalesce(a.from_zone,''))='PWL1'),('UP','UP_IN','garments',upper(coalesce(a.to_location,''))like'%UNDERPRINT%'),('UP','UP_OUT','garments',upper(coalesce(a.from_location,''))like'%UNDERPRINT%'and upper(coalesce(a.to_location,''))not like'%UNDERPRINT%'))v(area,metric,unit,accepted)where accepted)m
left join lateral(select s.* from shift_rules s where s.organization_id=a.organization_id and s.active and s.effective_from<=(a.event_at at time zone'Australia/Brisbane')::date and(s.effective_to is null or s.effective_to>=(a.event_at at time zone'Australia/Brisbane')::date)and s.weekday=extract(isodow from case when s.cross_midnight and(a.event_at at time zone'Australia/Brisbane')::time<s.end_time then(a.event_at at time zone'Australia/Brisbane')::date-1 else(a.event_at at time zone'Australia/Brisbane')::date end)and(case when s.cross_midnight then(a.event_at at time zone'Australia/Brisbane')::time>=s.start_time or(a.event_at at time zone'Australia/Brisbane')::time<s.end_time else(a.event_at at time zone'Australia/Brisbane')::time>=s.start_time and(a.event_at at time zone'Australia/Brisbane')::time<s.end_time end)order by s.effective_from desc limit 1)r on true where a.organization_id=p_organization_id and a.production_units>0 on conflict do nothing;get diagnostics affected=row_count;return affected;end$$;
revoke all on function rebuild_production_events(uuid)from public,anon,authenticated;grant execute on function rebuild_production_events(uuid)to service_role;
create or replace function ingest_sync_batch(payload jsonb)returns uuid language plpgsql security definer set search_path=public as $$declare batch_id uuid;audit_count integer;begin insert into sync_batches(organization_id,status,connector_version)values((payload->>'organizationId')::uuid,'running',payload->>'connectorVersion')returning id into batch_id;begin
insert into source_orders(organization_id,sync_batch_id,order_no,date_received,date_due,date_released,source_status,source_sub_status,customer_code,customer_name,ship_to_name,customer_state,city,delivery_desc,client_so_number,source_priority,site,source_updated_at)select(payload->>'organizationId')::uuid,batch_id,x."orderNo",x."dateReceived",x."dateDue",x."dateReleased",x."sourceStatus",x."sourceSubStatus",x."customerCode",x."customerName",x."shipToName",x."customerState",x.city,x."deliveryDesc",x."clientSoNumber",x."sourcePriority",x.site,x."sourceUpdatedAt"from jsonb_to_recordset(payload->'orders')x("orderNo"text,"dateReceived"timestamptz,"dateDue"timestamptz,"dateReleased"timestamptz,"sourceStatus"text,"sourceSubStatus"text,"customerCode"text,"customerName"text,"shipToName"text,"customerState"text,city text,"deliveryDesc"text,"clientSoNumber"text,"sourcePriority"integer,site text,"sourceUpdatedAt"timestamptz);
insert into source_workbank_items(organization_id,sync_batch_id,source_row_id,order_no,customer_code,customer_name,source_due_at,from_location,from_zone,to_location,from_pack_id,to_pack_id,source_priority,product_code,product_description,product_group,source_qty,source_weight,production_units,prints_per_garment,queue,task)select(payload->>'organizationId')::uuid,batch_id,x.*from jsonb_to_recordset(payload->'workbank')x("sourceRowId"text,"orderNo"text,"customerCode"text,"customerName"text,"sourceDueAt"timestamptz,"fromLocation"text,"fromZone"text,"toLocation"text,"fromPackId"text,"toPackId"text,"sourcePriority"integer,"productCode"text,"productDescription"text,"productGroup"text,"sourceQty"numeric,"sourceWeight"numeric,"productionUnits"numeric,"printsPerGarment"numeric,queue text,task text);
insert into source_stock_items(organization_id,sync_batch_id,product,pack_id,location,source_zone,source_timestamp,source_qty,source_weight,production_units)select(payload->>'organizationId')::uuid,batch_id,x.*from jsonb_to_recordset(payload->'stock')x(product text,"packId"text,location text,"sourceZone"text,"sourceTimestamp"timestamptz,"sourceQty"numeric,"sourceWeight"numeric,"productionUnits"numeric);
insert into source_audit_events(organization_id,source_audit_id,order_no,username,from_zone,to_zone,from_location,to_location,product,from_pack_id,to_pack_id,source_qty,source_weight,production_units,event_at,raw_hash,queue,task)select(payload->>'organizationId')::uuid,x.*from jsonb_to_recordset(payload->'auditEvents')x("sourceAuditId"text,"orderNo"text,username text,"fromZone"text,"toZone"text,"fromLocation"text,"toLocation"text,product text,"fromPackId"text,"toPackId"text,"sourceQty"numeric,"sourceWeight"numeric,"productionUnits"numeric,"eventAt"timestamptz,"rawHash"text,queue text,task text)on conflict do nothing;get diagnostics audit_count=row_count;perform rebuild_production_events((payload->>'organizationId')::uuid);update sync_batches set status='completed',completed_at=now(),orders_count=jsonb_array_length(payload->'orders'),workbank_count=jsonb_array_length(payload->'workbank'),stock_count=jsonb_array_length(payload->'stock'),audit_new_count=audit_count where id=batch_id;exception when others then update sync_batches set status='failed',error_message=left(sqlerrm,1000)where id=batch_id;raise;end;return batch_id;end$$;
alter function ingest_sync_batch(jsonb)set statement_timeout='120s';revoke all on function ingest_sync_batch(jsonb)from public,anon,authenticated;grant execute on function ingest_sync_batch(jsonb)to service_role;
